version: '3.2'

services:
  eos-node:
    image: ${DOCKER_HUB_LOGIN}/eos:mainnet
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/diadata/blockchain-scrapers/blockchains/eos/node/Dockerfile-node
    volumes:
      - eosio:/opt/eosio
    logging:
      options:
        max-size: "50m"
    cap_add:
      - IPC_LOCK
    stop_grace_period: 10m
    networks:
      - scrapers-network

  eos:
    image: ${DOCKER_HUB_LOGIN}/eos:scraper
    depends_on:
      - eos-node
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/diadata/blockchain-scrapers/blockchains/eos/node/Dockerfile
    networks:
      - scrapers-network
    logging:
      options:
        max-size: "50m"
    networks:
      - scrapers-network
    secrets:
      - api_diadata

secrets:
  api_diadata:
    file: $GOPATH/src/github.com/diadata-org/diadata/blockchain-scrapers/config/secrets/api_diadata.json

volumes: 
  eosio:
    external: true

networks: 
  scrapers-network: