version: '3.2'
services:

  influxdb2:
    environment:
      - EXEC_MODE=production

    image: influxdb:1.8.3
    volumes:
      - /home/srv/influxdb-2:/var/lib/influxdb
    networks:
      - influxdb2-network
    environment:
      INFLUXDB_HTTP_MAX_BODY_SIZE: 0
      INFLUXDB_MONITOR_STORE_ENABLED: "FALSE"
      # Default is 1g
      INFLUXDB_DATA_CACHE_MAX_MEMORY_SIZE: 4g
      # Default is 1m
      INFLUXDB_DATA_MAX_INDEX_LOG_FILE_SIZE: 8m
    logging:
      options:
        max-size: "50m" 
  
    deploy:
      resources:
        limits:
          memory: 100G


networks:
  influxdb2-network:
    driver: overlay
    attachable: true
