version: '3.2'
services:

  influxmigration:
    build:
      context: ../../../..
      dockerfile: github.com/diadata-org/diadata/build/Dockerfile-influxMigration
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_influxmigration:latest
    command: /bin/influxMigration
    networks:
      - influxdb-network
      - influxdb2-network
      - postgres-network
    logging:
      options:
        max-size: "50m"
    secrets:
      - postgres_credentials
    volumes:
      - /home/srv/config:/config
    environment:
      - EXEC_MODE=production
      - INFLUX_READ_URL=http://influxdb:8086
      - INFLUX_WRITE_URL=http://influxdb-2:8086
      - INFLUX_TABLE_ORIGIN=trades
      - INFLUX_TABLE_DESTINATION=tradesTmp
      - TIME_FINAL=1636618800
      - INFLUX_MIGRATION_TESTMODE=false
  
secrets:
  postgres_credentials:
    file: ../secrets/postgres_credentials.txt

networks:
  postgres-network:
    external:
        name: postgres_postgres-network
  influxdb-network:
    external:
        name: influxdb_influxdb-network
  influxdb2-network:
    external:
        name: influxdb-2_influxdb2-network