version: "3.2"
services:
  graphqlserver:
    environment:
      - EXEC_MODE=production
    ports:
      - "1111:1111"
    build:
      context: ../../../..
      dockerfile: github.com/diadata-org/diadata/build/Dockerfile-graphqlServer
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_graphqlserver:latest
    networks:
      - redis-network
      - influxdb-network

    logging:
      options:
        max-size: "50m"

networks:
  redis-network:
    external:
      name: redis_redis-network
  influxdb-network:
    external:
      name: influxdb_influxdb-network
