FROM golang:latest as build

WORKDIR $GOPATH

COPY . .

WORKDIR $GOPATH/src/github.com/diadata-org/api-golang/blockchain-scrapers/blockchains/litecoin/scrapers/ltc

RUN go install

FROM gcr.io/distroless/base

COPY --from=build /go/bin/ltc /bin/ltc

CMD ["ltc"]
