run:
  timeout: 2m
  tests: false

linters:
  enable:
    - errcheck
    - gosimple  
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0