package helpers

func NameForSymbol(symbol string) string {
	switch symbol {
	case "BTC":
		return "Bitcoin"
	case "LTC":
		return "Litecoin"
	case "NMC":
		return "Namecoin"
	case "TRC":
		return "Terracoin"
	case "PPC":
		return "Peercoin"
	case "NVC":
		return "Novacoin"
	case "FTC":
		return "Feathercoin"
	case "MNC":
		return "Mincoin"
	case "FRC":
		return "Freicoin"
	case "IXC":
		return "Ixcoin"
	case "BTB":
		return "BitBar"
	case "WDC":
		return "WorldCoin"
	case "DGC":
		return "Digitalcoin"
	case "GLD":
		return "GoldCoin"
	case "ARG":
		return "Argentum"
	case "FST":
		return "Fastcoin"
	case "BTG":
		return "Bitgem"
	case "PXC":
		return "Phoenixcoin"
	case "MEC":
		return "Megacoin"
	case "IFC":
		return "Infinitecoin"
	case "XPM":
		return "Primecoin"
	case "ANC":
		return "Anoncoin"
	case "CSC":
		return "CasinoCoin"
	case "CBX":
		return "Bullion"
	case "EMD":
		return "Emerald Crypto"
	case "GLC":
		return "GlobalCoin"
	case "XRP":
		return "XRP"
	case "QRK":
		return "Quark"
	case "ZET":
		return "Zetacoin"
	case "SRC":
		return "SecureCoin"
	case "SXC":
		return "Sexcoin"
	case "TAG":
		return "TagCoin"
	case "I0C":
		return "I0Coin"
	case "FLO":
		return "FlorinCoin"
	case "NXT":
		return "Nxt"
	case "UNO":
		return "Unobtanium"
	case "XJO":
		return "Joulecoin"
	case "DTC":
		return "Datacoin"
	case "BET":
		return "BetaCoin"
	case "GDC":
		return "GrandCoin"
	case "DEM":
		return "Deutsche eMark"
	case "DOGE":
		return "Dogecoin"
	case "NET":
		return "NetCoin"
	case "PHS":
		return "Philosopher Stones"
	case "DMD":
		return "Diamond"
	case "HBN":
		return "HoboNickels"
	case "TGC":
		return "Tigercoin"
	case "ORB":
		return "Orbitcoin"
	case "OMNI":
		return "Omni"
	case "CAT":
		return "Catcoin"
	case "TIPS":
		return "FedoraCoin"
	case "RPC":
		return "RonPaulCoin"
	case "MOON":
		return "Mooncoin"
	case "DIME":
		return "Dimecoin"
	case "42":
		return "42-coin"
	case "VTC":
		return "Vertcoin"
	case "KDC":
		return "KlondikeCoin"
	case "RED":
		return "RedCoin"
	case "DGB":
		return "DigiByte"
	case "SMC":
		return "SmartCoin"
	case "TES":
		return "TeslaCoin"
	case "NOBL":
		return "NobleCoin"
	case "RDD":
		return "ReddCoin"
	case "NYAN":
		return "Nyancoin"
	case "UTC":
		return "UltraCoin"
	case "POT":
		return "PotCoin"
	case "BLC":
		return "Blakecoin"
	case "MAX":
		return "MaxCoin"
	case "Q2C":
		return "QubitCoin"
	case "HUC":
		return "HunterCoin"
	case "DASH":
		return "Dash"
	case "XCP":
		return "Counterparty"
	case "CACH":
		return "CacheCoin"
	case "TOP":
		return "TopCoin"
	case "ICN":
		return "iCoin"
	case "MINT":
		return "Mintcoin"
	case "ARI":
		return "Aricoin"
	case "DOPE":
		return "DopeCoin"
	case "AUR":
		return "Auroracoin"
	case "ANI":
		return "Animecoin"
	case "PTC":
		return "Pesetacoin"
	case "MARS":
		return "Marscoin"
	case "CASH":
		return "Cashcoin"
	case "RIC":
		return "Riecoin"
	case "PND":
		return "Pandacoin"
	case "MAZA":
		return "MAZA"
	case "UFO":
		return "Uniform Fiscal Object"
	case "BLK":
		return "BlackCoin"
	case "LTB":
		return "LiteBar"
	case "PHO":
		return "Photon"
	case "ZEIT":
		return "Zeitcoin"
	case "XMY":
		return "Myriad"
	case "NOTE":
		return "DNotes"
	case "SKC":
		return "Skeincoin"
	case "EMC2":
		return "Einsteinium"
	case "BTCS":
		return "Bitcoin Scrypt"
	case "CNO":
		return "Coin(O)"
	case "ECC":
		return "ECC"
	case "MONA":
		return "MonaCoin"
	case "RBY":
		return "Rubycoin"
	case "BELA":
		return "Bela"
	case "FLT":
		return "FlutterCoin"
	case "888":
		return "OctoCoin"
	case "FAIR":
		return "FairCoin"
	case "SLR":
		return "SolarCoin"
	case "EFL":
		return "e-Gulden"
	case "NLG":
		return "Gulden"
	case "PLC":
		return "Polcoin"
	case "GRS":
		return "Groestlcoin"
	case "XPD":
		return "PetroDollar"
	case "PLNC":
		return "PLNcoin"
	case "XWC":
		return "WhiteCoin"
	case "AC":
		return "AsiaCoin"
	case "POP":
		return "PopularCoin"
	case "BITS":
		return "Bitstar"
	case "QBC":
		return "Quebecoin"
	case "CCN":
		return "CannaCoin"
	case "SLOTH":
		return "Slothcoin"
	case "BLU":
		return "BlueCoin"
	case "MAID":
		return "MaidSafeCoin"
	case "XBC":
		return "Bitcoin Plus"
	case "TALK":
		return "BTCtalkcoin"
	case "NYC":
		return "NewYorkCoin"
	case "CDN":
		return "Canada eCoin"
	case "GUN":
		return "Guncoin"
	case "PINK":
		return "PinkCoin"
	case "DRM":
		return "Dreamcoin"
	case "CFC":
		return "CoffeeCoin"
	case "ENRG":
		return "Energycoin"
	case "VRC":
		return "VeriCoin"
	case "TEK":
		return "TEKcoin"
	case "XMR":
		return "Monero"
	case "LCP":
		return "Litecoin Plus"
	case "CURE":
		return "Curecoin"
	case "UNB":
		return "UnbreakableCoin"
	case "CRYPT":
		return "CryptCoin"
	case "SUPER":
		return "SuperCoin"
	case "BOST":
		return "BoostCoin"
	case "HYPER":
		return "Hyper"
	case "BTQ":
		return "BitQuark"
	case "MOTO":
		return "Motocoin"
	case "CLOAK":
		return "CloakCoin"
	case "BSD":
		return "BitSend"
	case "C2":
		return "Coin2.1"
	case "FCN":
		return "Fantomcoin"
	case "BCN":
		return "Bytecoin"
	case "ABY":
		return "ArtByte"
	case "NAV":
		return "NavCoin"
	case "GRN":
		return "Granite"
	case "DON":
		return "Donationcoin"
	case "PIGGY":
		return "Piggycoin"
	case "START":
		return "Startcoin"
	case "KORE":
		return "Kore"
	case "XDN":
		return "DigitalNote"
	case "BBR":
		return "Boolberry"
	case "SHA":
		return "SHACoin"
	case "BLZ":
		return "BlazeCoin"
	case "THC":
		return "HempCoin"
	case "BRIT":
		return "BritCoin"
	case "XST":
		return "Stealth"
	case "TRUST":
		return "TrustPlus"
	case "CLAM":
		return "Clams"
	case "QTL":
		return "Quatloo"
	case "BTS":
		return "BitShares"
	case "BTCD":
		return "BitcoinDark"
	case "TRK":
		return "Truckcoin"
	case "VIA":
		return "Viacoin"
	case "TRI":
		return "Triangles"
	case "IOC":
		return "I/O Coin"
	case "XCN":
		return "Cryptonite"
	case "CARBON":
		return "Carboncoin"
	case "CANN":
		return "CannabisCoin"
	case "XLM":
		return "Stellar"
	case "TIT":
		return "Titcoin"
	case "VTA":
		return "Virtacoin"
	case "HYP":
		return "HyperStake"
	case "J":
		return "Joincoin"
	case "SYS":
		return "Syscoin"
	case "BTM":
		return "Bytom"
	case "HAL":
		return "Halcyon"
	case "SJCX":
		return "Storjcoin X"
	case "NEOS":
		return "NeosCoin"
	case "EMC":
		return "Emercoin"
	case "RBBT":
		return "RabbitCoin"
	case "BURST":
		return "Burst"
	case "GAME":
		return "GameCredits"
	case "WSX":
		return "WeAreSatoshi"
	case "UBQ":
		return "Ubiq"
	case "BUN":
		return "BunnyCoin"
	case "OPAL":
		return "Opal"
	case "ACOIN":
		return "Acoin"
	case "FLDC":
		return "FoldingCoin"
	case "BITUSD":
		return "bitUSD"
	case "BITCNY":
		return "bitCNY"
	case "BITBTC":
		return "bitBTC"
	case "USNBT":
		return "NuBits"
	case "SLG":
		return "Sterlingcoin"
	case "XMG":
		return "Magi"
	case "EXCL":
		return "ExclusiveCoin"
	case "TROLL":
		return "Trollcoin"
	case "UNITY":
		return "SuperNET"
	case "BSTY":
		return "GlobalBoost-Y"
	case "DP":
		return "DigitalPrice"
	case "PXI":
		return "Prime-XI"
	case "DSH":
		return "Dashcoin"
	case "AU":
		return "AurumCoin"
	case "STV":
		return "Sativacoin"
	case "XVG":
		return "Verge"
	case "NSR":
		return "NuShares"
	case "SPR":
		return "SpreadCoin"
	case "RBT":
		return "Rimbit"
	case "MUE":
		return "MonetaryUnit"
	case "BLOCK":
		return "Blocknet"
	case "GAP":
		return "Gapcoin"
	case "TTC":
		return "TittieCoin"
	case "CRW":
		return "Crown"
	case "BAY":
		return "BitBay"
	case "GCN":
		return "GCN Coin"
	case "XQN":
		return "Quotient"
	case "BYC":
		return "Bytecent"
	case "BCF":
		return "Bitcoin Fast"
	case "OK":
		return "OKCash"
	case "XPY":
		return "PayCoin"
	case "VTR":
		return "vTorrent"
	case "BITGOLD":
		return "bitGold"
	case "UIS":
		return "Unitus"
	case "GP":
		return "GoldPieces"
	case "COVAL":
		return "Circuits of Value"
	case "NXS":
		return "Nexus"
	case "SOON":
		return "SoonCoin"
	case "METAL":
		return "MetalCoin"
	case "NKA":
		return "IncaKoin"
	case "SMLY":
		return "SmileyCoin"
	case "MAC":
		return "Machinecoin"
	case "BITSILVER":
		return "bitSilver"
	case "DOT":
		return "Dotcoin"
	case "KOBO":
		return "Kobocoin"
	case "CON":
		return "PayCon"
	case "BITB":
		return "Bean Cash"
	case "GEO":
		return "GeoCoin"
	case "USDT":
		return "Tether"
	case "WBB":
		return "Wild Beast Block"
	case "GRC":
		return "GridCoin"
	case "XVC":
		return "Vcash"
	case "XCO":
		return "X-Coin"
	case "SAK":
		return "Sharkcoin"
	case "LDOGE":
		return "LiteDoge"
	case "SONG":
		return "SongCoin"
	case "LOG":
		return "Woodcoin"
	case "CRAVE":
		return "Crave"
	case "PURA":
		return "Pura"
	case "XEM":
		return "NEM"
	case "8BIT":
		return "8Bit"
	case "LEA":
		return "LeaCoin"
	case "NTRN":
		return "Neutron"
	case "XAUR":
		return "Xaurum"
	case "CF":
		return "Californium"
	case "AIB":
		return "Advanced Internet Blocks"
	case "EGG":
		return "EggCoin"
	case "SPHR":
		return "Sphere"
	case "MEDIC":
		return "MedicCoin"
	case "BUB":
		return "Bubble"
	case "MUSE":
		return "MUSE"
	case "UNIT":
		return "Universal Currency"
	case "SHELL":
		return "ShellCoin"
	case "CTO":
		return "Crypto"
	case "PKB":
		return "ParkByte"
	case "ARB":
		return "ARbit"
	case "GAM":
		return "Gambit"
	case "BTA":
		return "Bata"
	case "ADC":
		return "AudioCoin"
	case "SNRG":
		return "Synergy"
	case "BITEUR":
		return "bitEUR"
	case "UNIC":
		return "UniCoin"
	case "FJC":
		return "FujiCoin"
	case "ERC":
		return "EuropeCoin"
	case "FUNK":
		return "The Cypherfunks"
	case "HXX":
		return "Hexx"
	case "XRA":
		return "Ratecoin"
	case "CREVA":
		return "CrevaCoin"
	case "IRL":
		return "IrishCoin"
	case "ZNY":
		return "Bitzeny"
	case "BSC":
		return "BowsCoin"
	case "ACP":
		return "AnarchistsPrime"
	case "CPN":
		return "CompuCoin"
	case "CHC":
		return "ChainCoin"
	case "SPRTS":
		return "Sprouts"
	case "HNC":
		return "Helleniccoin"
	case "CPC":
		return "Capricoin"
	case "FLAX":
		return "Flaxscript"
	case "MANNA":
		return "Manna"
	case "AXIOM":
		return "Axiom"
	case "LEO":
		return "LEOcoin"
	case "AEON":
		return "Aeon"
	case "ETH":
		return "Ethereum"
	case "SJW":
		return "SJWCoin"
	case "TX":
		return "TransferCoin"
	case "GCC":
		return "GuccioneCoin"
	case "AMS":
		return "AmsterdamCoin"
	case "EUC":
		return "Eurocoin"
	case "SC":
		return "Siacoin"
	case "GCR":
		return "Global Currency Reserve"
	case "SHIFT":
		return "Shift"
	case "VEC2":
		return "VectorAI"
	case "BOLI":
		return "Bolivarcoin"
	case "SPACE":
		return "SpaceCoin"
	case "BCY":
		return "Bitcrystals"
	case "PAK":
		return "Pakcoin"
	case "INFX":
		return "Influxcoin"
	case "EXP":
		return "Expanse"
	case "SIB":
		return "SIBCoin"
	case "ISL":
		return "IslaCoin"
	case "SWING":
		return "Swing"
	case "FCT":
		return "Factom"
	case "DUO":
		return "ParallelCoin"
	case "SANDG":
		return "Save and Gain"
	case "PR":
		return "Prototanium"
	case "CUBE":
		return "DigiCube"
	case "REP":
		return "Augur"
	case "SHND":
		return "StrongHands"
	case "$PAC":
		return "PACcoin"
	case "1337":
		return "Elite"
	case "$$$":
		return "Money"
	case "SOIL":
		return "SOILcoin"
	case "SCRT":
		return "SecretCoin"
	case "DFT":
		return "DraftCoin"
	case "OBITS":
		return "OBITS"
	case "AMP":
		return "Synereo"
	case "CLUB":
		return "ClubCoin"
	case "ADZ":
		return "Adzcoin"
	case "MOIN":
		return "Moin"
	case "AV":
		return "AvatarCoin"
	case "RC":
		return "RussiaCoin"
	case "EGC":
		return "EverGreenCoin"
	case "CRB":
		return "Creditbit"
	case "RADS":
		return "Radium"
	case "LTCR":
		return "Litecred"
	case "YOC":
		return "Yocoin"
	case "SLS":
		return "SaluS"
	case "FRN":
		return "Francs"
	case "EVIL":
		return "Evil Coin"
	case "DCR":
		return "Decred"
	case "PIVX":
		return "PIVX"
	case "SAFEX":
		return "Safe Exchange Coin"
	case "RBIES":
		return "Rubies"
	case "ADCN":
		return "Asiadigicoin"
	case "KLC":
		return "KiloCoin"
	case "TRUMP":
		return "TrumpCoin"
	case "MEME":
		return "Memetic / PepeCoin"
	case "XCT":
		return "C-Bit"
	case "IMS":
		return "Independent Money System"
	case "HODL":
		return "HOdlcoin"
	case "BIGUP":
		return "BigUp"
	case "NEVA":
		return "NevaCoin"
	case "BUMBA":
		return "BumbaCoin"
	case "RVR":
		return "RevolutionVR"
	case "PEX":
		return "PosEx"
	case "CAB":
		return "Cabbage"
	case "MOJO":
		return "MojoCoin"
	case "GMX":
		return "GoldMaxCoin"
	case "LSK":
		return "Lisk"
	case "EDRC":
		return "EDRCoin"
	case "POST":
		return "PostCoin"
	case "BERN":
		return "BERNcash"
	case "QWARK":
		return "Qwark"
	case "DGD":
		return "DigixDAO"
	case "STEEM":
		return "Steem"
	case "FANS":
		return "Fantasy Cash"
	case "ESP":
		return "Espers"
	case "FUZZ":
		return "FuzzBalls"
	case "XHI":
		return "HiCoin"
	case "ARCO":
		return "AquariusCoin"
	case "XBTC21":
		return "Bitcoin 21"
	case "EL":
		return "Elcoin"
	case "ZUR":
		return "Zurcoin"
	case "611":
		return "SixEleven"
	case "2GIVE":
		return "2GIVE"
	case "XPTX":
		return "PlatinumBAR"
	case "ABC":
		return "Alphabit"
	case "LANA":
		return "LanaCoin"
	case "PONZI":
		return "PonziCoin"
	case "TESLA":
		return "TeslaCoilCoin"
	case "MXT":
		return "MarteXcoin"
	case "NLX":
		return "Nullex"
	case "RICHX":
		return "RichCoin"
	case "PRM":
		return "PrismChain"
	case "WAVES":
		return "Waves"
	case "ICOO":
		return "ICO OpenLedger"
	case "PWR":
		return "Powercoin"
	case "ION":
		return "ION"
	case "HVCO":
		return "High Voltage"
	case "MNM":
		return "Mineum"
	case "XRE":
		return "RevolverCoin"
	case "GB":
		return "GoldBlocks"
	case "BRK":
		return "Breakout"
	case "DBTC":
		return "Debitcoin"
	case "CMT":
		return "Comet"
	case "RISE":
		return "Rise"
	case "CHESS":
		return "ChessCoin"
	case "LBC":
		return "LBRY Credits"
	case "PUT":
		return "PutinCoin"
	case "BRX":
		return "Breakout Stake"
	case "SYNX":
		return "Syndicate"
	case "CJ":
		return "Cryptojacks"
	case "HEAT":
		return "HEAT"
	case "LIR":
		return "LetItRide"
	case "SBD":
		return "Steem Dollars"
	case "ARDR":
		return "Ardor"
	case "ETC":
		return "Ethereum Classic"
	case "808":
		return "808Coin"
	case "BIT":
		return "First Bitcoin"
	case "ELE":
		return "Elementrem"
	case "GAIN":
		return "UGAIN"
	case "KRB":
		return "Karbo"
	case "VPRC":
		return "VapersCoin"
	case "STRAT":
		return "Stratis"
	case "PRES":
		return "President Trump"
	case "ACES":
		return "Aces"
	case "GARY":
		return "President Johnson"
	case "TAJ":
		return "TajCoin"
	case "EDR":
		return "E-Dinar Coin"
	case "ATX":
		return "Artex Coin"
	case "XP":
		return "Experience Points"
	case "VLT":
		return "Veltor"
	case "KB3":
		return "B3Coin"
	case "GOLF":
		return "Golfcoin"
	case "NEO":
		return "NEO"
	case "LMC":
		return "LoMoCoin"
	case "BTDX":
		return "Bitcloud"
	case "NLC2":
		return "NoLimitCoin"
	case "VRM":
		return "VeriumReserve"
	case "ZYD":
		return "Zayedcoin"
	case "JIN":
		return "Jin Coin"
	case "XTO":
		return "Tao"
	case "PLU":
		return "Pluton"
	case "TELL":
		return "Tellurion"
	case "DLC":
		return "Dollarcoin"
	case "MST":
		return "MustangCoin"
	case "XBTS":
		return "Beatcoin"
	case "PROUD":
		return "PROUD Money"
	case "SEQ":
		return "Sequence"
	case "OMC":
		return "Omicron"
	case "1ST":
		return "FirstBlood"
	case "PEPECASH":
		return "Pepe Cash"
	case "SNGLS":
		return "SingularDTV"
	case "XZC":
		return "ZCoin"
	case "RCN":
		return "Rcoin"
	case "ATOM":
		return "Atomic Coin"
	case "JOBS":
		return "JobsCoin"
	case "TRIG":
		return "Triggers"
	case "SKR":
		return "Sakuracoin"
	case "LEVO":
		return "Levocoin"
	case "ARC":
		return "Advanced Technology Coin"
	case "QBT":
		return "Cubits"
	case "DMC":
		return "DynamicCoin"
	case "ZEC":
		return "Zcash"
	case "ASAFE2":
		return "AllSafe"
	case "BIP":
		return "BipCoin"
	case "ZCL":
		return "ZClassic"
	case "ZOI":
		return "Zoin"
	case "WA":
		return "WA Space"
	case "LKK":
		return "Lykke"
	case "GNT":
		return "Golem"
	case "ZMC":
		return "ZetaMicron"
	case "BTCR":
		return "Bitcurrency"
	case "REGA":
		return "Regacoin"
	case "IOP":
		return "Internet of People"
	case "VRS":
		return "Veros"
	case "HUSH":
		return "Hush"
	case "KURT":
		return "Kurrent"
	case "XCRE":
		return "Creatio"
	case "XRC":
		return "Rawcoin"
	case "PASC":
		return "Pascal Coin"
	case "ENT":
		return "Eternity"
	case "INCNT":
		return "Incent"
	case "DCT":
		return "DECENT"
	case "GOLOS":
		return "Golos"
	case "NXC":
		return "Nexium"
	case "VSL":
		return "vSlice"
	case "DOLLAR":
		return "Dollar Online"
	case "VLTC":
		return "Vault Coin"
	case "PCS":
		return "Pabyosi Coin (Special)"
	case "TCOIN":
		return "T-coin"
	case "GBYTE":
		return "Byteball Bytes"
	case "POSW":
		return "PoSW Coin"
	case "LUNA":
		return "Luna Coin"
	case "FRGC":
		return "Fargocoin"
	case "WINGS":
		return "Wings"
	case "DIX":
		return "Dix Asset"
	case "DAR":
		return "Darcrus"
	case "IFLT":
		return "InflationCoin"
	case "XSPEC":
		return "Spectrecoin"
	case "XSTC":
		return "Safe Trade Coin"
	case "LDCN":
		return "LandCoin"
	case "BENJI":
		return "BenjiRolls"
	case "CCRB":
		return "CryptoCarbon"
	case "VIDZ":
		return "PureVidz"
	case "BCC":
		return "BitConnect"
	case "ICOB":
		return "ICOBID"
	case "IBANK":
		return "iBank"
	case "MKR":
		return "Maker"
	case "DRS":
		return "Digital Rupees"
	case "KMD":
		return "Komodo"
	case "FRST":
		return "FirstCoin"
	case "MGM":
		return "Magnum"
	case "TSE":
		return "Tattoocoin (Standard Edition)"
	case "SFC":
		return "Solarflarecoin"
	case "ZBC":
		return "Zilbercoin"
	case "WCT":
		return "Waves Community Token"
	case "ICON":
		return "Iconic"
	case "KUSH":
		return "KushCoin"
	case "ACN":
		return "Avoncoin"
	case "BOAT":
		return "BOAT"
	case "ERY":
		return "Eryllium"
	case "ELS":
		return "Elysium"
	case "GBG":
		return "Golos Gold"
	case "CNT":
		return "Centurion"
	case "MAR":
		return "Marijuanacoin"
	case "MSCN":
		return "Master Swiscoin"
	case "MLN":
		return "Melon"
	case "ALL":
		return "Allion"
	case "PRC":
		return "PRCoin"
	case "TIME":
		return "Chronobank"
	case "ARGUS":
		return "Argus"
	case "RNS":
		return "Renos"
	case "UR":
		return "UR"
	case "SWT":
		return "Swarm City"
	case "PIE":
		return "PIECoin"
	case "MARX":
		return "MarxCoin"
	case "VISIO":
		return "Visio"
	case "NANO":
		return "Nano"
	case "LVPS":
		return "LevoPlus"
	case "GEERT":
		return "GeertCoin"
	case "PASL":
		return "Pascal Lite"
	case "MILO":
		return "MiloCoin"
	case "MUSIC":
		return "Musicoin"
	case "ZER":
		return "Zero"
	case "BIOB":
		return "BioBar"
	case "HONEY":
		return "Honey"
	case "NETKO":
		return "Netko"
	case "ARK":
		return "Ark"
	case "DYN":
		return "Dynamic"
	case "TKS":
		return "Tokes"
	case "MER":
		return "Mercury"
	case "TAAS":
		return "TaaS"
	case "SOAR":
		return "Soarcoin"
	case "EDG":
		return "Edgeless"
	case "B@":
		return "Bankcoin"
	case "ZSE":
		return "ZSEcoin"
	case "WORM":
		return "HealthyWormCoin"
	case "DTB":
		return "Databits"
	case "UNI":
		return "Universe"
	case "XLR":
		return "Solaris"
	case "IMX":
		return "Impact"
	case "TSTR":
		return "Tristar Coin"
	case "XAS":
		return "Asch"
	case "DBIX":
		return "DubaiCoin"
	case "KED":
		return "Darsek"
	case "GUP":
		return "Matchpool"
	case "USC":
		return "Ultimate Secure Cash"
	case "ECN":
		return "E-coin"
	case "SKY":
		return "Skycoin"
	case "BLAZR":
		return "BlazerCoin"
	case "ATMOS":
		return "Atmos"
	case "EMV":
		return "Ethereum Movie Venture"
	case "INPAY":
		return "InPay"
	case "HPC":
		return "Happycoin"
	case "ZENI":
		return "Zennies"
	case "CXT":
		return "Coinonat"
	case "XOT":
		return "Internet of Things"
	case "CONX":
		return "Concoin"
	case "XBY":
		return "XTRABYTES"
	case "RLC":
		return "iExec RLC"
	case "TRST":
		return "WeTrust"
	case "DEUS":
		return "DeusCoin"
	case "ALT":
		return "Altcoin"
	case "WGO":
		return "WavesGo"
	case "MCRN":
		return "MACRON"
	case "TLE":
		return "Tattoocoin (Limited Edition)"
	case "PROC":
		return "ProCurrency"
	case "SCS":
		return "SpeedCash"
	case "BTX":
		return "Bitcore"
	case "VOLT":
		return "Bitvolt"
	case "LUN":
		return "Lunyr"
	case "GNO":
		return "Gnosis"
	case "TKN":
		return "TokenCard"
	case "RAIN":
		return "Condensate"
	case "GPL":
		return "Gold Pressed Latinum"
	case "HMQ":
		return "Humaniq"
	case "FUNC":
		return "FUNCoin"
	case "ITI":
		return "iTicoin"
	case "MNE":
		return "Minereum"
	case "CNNC":
		return "Cannation"
	case "CREA":
		return "Creativecoin"
	case "DICE":
		return "Etheroll"
	case "INSN":
		return "InsaneCoin"
	case "HALLO":
		return "Halloween Coin"
	case "ANT":
		return "Aragon"
	case "PZM":
		return "PRIZM"
	case "RLT":
		return "RouletteToken"
	case "QTUM":
		return "Qtum"
	case "ECO":
		return "EcoCoin"
	case "EQT":
		return "EquiTrader"
	case "DMB":
		return "Digital Money Bits"
	case "APX":
		return "APX"
	case "MCAP":
		return "MCAP"
	case "NANOX":
		return "Project-X"
	case "MAY":
		return "Theresa May Coin"
	case "SUMO":
		return "Sumokoin"
	case "ZENGOLD":
		return "ZenGold"
	case "BAT":
		return "Basic Attention Token"
	case "ZEN":
		return "ZenCash"
	case "ETBS":
		return "Ethbits"
	case "AE":
		return "Aeternity"
	case "V":
		return "Version"
	case "ETP":
		return "Metaverse ETP"
	case "EBST":
		return "eBoost"
	case "ADK":
		return "Aidos Kuneen"
	case "STEX":
		return "STEX"
	case "PTOY":
		return "Patientory"
	case "QAU":
		return "Quantum"
	case "VERI":
		return "Veritaseum"
	case "ECA":
		return "Electra"
	case "QRL":
		return "Quantum Resistant Ledger"
	case "ETT":
		return "EncryptoTel WAVES"
	case "MGO":
		return "MobileGo"
	case "AMMO":
		return "Ammo Reloaded"
	case "NRO":
		return "Neuro"
	case "PPY":
		return "Peerplays"
	case "MIOTA":
		return "IOTA"
	case "MYST":
		return "Mysterium"
	case "MORE":
		return "More Coin"
	case "SNM":
		return "SONM"
	case "LINX":
		return "Linx"
	case "ZRC":
		return "ZrCoin"
	case "BNT":
		return "Bancor"
	case "CHEAP":
		return "Cheapcoin"
	case "CFI":
		return "Cofound.it"
	case "GLT":
		return "GlobalToken"
	case "NMR":
		return "Numeraire"
	case "OTX":
		return "Octanox"
	case "UNIFY":
		return "Unify"
	case "XEL":
		return "Elastic"
	case "COUPE":
		return "Coupecoin"
	case "MRT":
		return "Miners' Reward Token"
	case "BITOK":
		return "Bitok"
	case "KNC":
		return "KingN Coin"
	case "DCY":
		return "Dinastycoin"
	case "XLC":
		return "Leviar"
	case "ONX":
		return "Onix"
	case "BTPL":
		return "Bitcoin Planet"
	case "GXS":
		return "GXChain"
	case "GOOD":
		return "Goodomy"
	case "ANTX":
		return "Antimatter"
	case "BRO":
		return "Bitradio"
	case "FLASH":
		return "Flash"
	case "FUN":
		return "FunFair"
	case "PAY":
		return "TenX"
	case "SNT":
		return "Status"
	case "CHAN":
		return "ChanCoin"
	case "EFYT":
		return "Ergo"
	case "BRIA":
		return "BriaCoin"
	case "EOS":
		return "EOS"
	case "TURBO":
		return "TurboCoin"
	case "ADX":
		return "AdEx"
	case "DNR":
		return "Denarius"
	case "STORJ":
		return "Storj"
	case "BNX":
		return "BnrtxCoin"
	case "SOCC":
		return "SocialCoin"
	case "ADT":
		return "adToken"
	case "MCO":
		return "MCO"
	case "PING":
		return "CryptoPing"
	case "UET":
		return "Useless Ethereum Token"
	case "WGR":
		return "Wagerr"
	case "SLEVIN":
		return "Slevin"
	case "ECOB":
		return "Ecobit"
	case "UNRC":
		return "UniversalRoyalCoin"
	case "PLBT":
		return "Polybius"
	case "GAS":
		return "Gas"
	case "SNC":
		return "SunContract"
	case "JET":
		return "Jetcoin"
	case "MTL":
		return "Metal"
	case "PPT":
		return "Populous"
	case "WOMEN":
		return "WomenCoin"
	case "VUC":
		return "Virta Unique Coin"
	case "BDL":
		return "Bitdeal"
	case "XID":
		return "Sphre AIR "
	case "DAXX":
		return "DaxxCoin"
	case "RUP":
		return "Rupee"
	case "GTC":
		return "Global Tour Coin"
	case "PCN":
		return "PeepCoin"
	case "HERO":
		return "Sovereign Hero"
	case "SAN":
		return "Santiment Network Token"
	case "OMG":
		return "OmiseGO"
	case "TER":
		return "TerraNova"
	case "CVCOIN":
		return "CVCoin"
	case "XRL":
		return "Rialto"
	case "LINDA":
		return "Linda"
	case "MBRS":
		return "Embers"
	case "CVC":
		return "Civic"
	case "ETHOS":
		return "Ethos"
	case "BTWTY":
		return "Bit20"
	case "STA":
		return "Starta"
	case "COAL":
		return "BitCoal"
	case "LBTC":
		return "LiteBitcoin"
	case "PART":
		return "Particl"
	case "SMART":
		return "SmartCash"
	case "SKIN":
		return "SkinCoin"
	case "BCH":
		return "Bitcoin Cash"
	case "HMC":
		return "HarmonyCoin"
	case "TOA":
		return "ToaCoin"
	case "PLR":
		return "Pillar"
	case "XRY":
		return "Royalties"
	case "SIGT":
		return "Signatum"
	case "CTIC2":
		return "Coimatic 2.0"
	case "OCT":
		return "OracleChain"
	case "BNB":
		return "Binance Coin"
	case "300":
		return "300 Token"
	case "PBT":
		return "Primalbase Token"
	case "CMPCO":
		return "CampusCoin"
	case "EMB":
		return "EmberCoin"
	case "IXT":
		return "iXledger"
	case "GSR":
		return "GeyserCoin"
	case "MSP":
		return "Mothership"
	case "ASN":
		return "Aseancoin"
	case "BIRDS":
		return "Birds"
	case "CRM":
		return "Cream"
	case "ERA":
		return "ERA"
	case "KEK":
		return "KekCoin"
	case "OAX":
		return "OAX"
	case "DNT":
		return "district0x"
	case "FYN":
		return "FundYourselfNow"
	case "STX":
		return "Stox"
	case "MINEX":
		return "Minex"
	case "CDT":
		return "Blox"
	case "WINK":
		return "Wink"
	case "MAO":
		return "Mao Zedong"
	case "BITCF":
		return "First Bitcoin Capital"
	case "NDC":
		return "NEVERDIE"
	case "TIX":
		return "Blocktix"
	case "DCN":
		return "Dentacoin"
	case "RUPX":
		return "Rupaya"
	case "SHDW":
		return "Shadow Token"
	case "ONION":
		return "DeepOnion"
	case "ADST":
		return "AdShares"
	case "DDF":
		return "DigitalDevelopersFund"
	case "BAS":
		return "BitAsean"
	case "DENT":
		return "Dent"
	case "MBI":
		return "Monster Byte"
	case "IFT":
		return "InvestFeed"
	case "XCXT":
		return "CoinonatX"
	case "RIYA":
		return "Etheriya"
	case "TCC":
		return "The ChampCoin"
	case "ZRX":
		return "0x"
	case "BLN":
		return "Bolenum"
	case "SMOKE":
		return "Smoke"
	case "YOYOW":
		return "YOYOW"
	case "GRWI":
		return "Growers International"
	case "MYB":
		return "MyBit Token"
	case "HSR":
		return "Hshare"
	case "VEN":
		return "VeChain"
	case "TFL":
		return "TrueFlip"
	case "XTD":
		return "XTD Coin"
	case "NAS":
		return "Nebulas"
	case "ATMC":
		return "ATMCoin"
	case "DALC":
		return "Dalecoin"
	case "PRN":
		return "Protean"
	case "ACC":
		return "AdCoin"
	case "BBP":
		return "BiblePay"
	case "BQ":
		return "bitqy"
	case "ACT":
		return "Achain"
	case "NAMO":
		return "NamoCoin"
	case "SIGMA":
		return "SIGMAcoin"
	case "XMCC":
		return "Monoeci"
	case "TNT":
		return "Tierion"
	case "WTC":
		return "Waltonchain"
	case "BRAT":
		return "BROTHER"
	case "ULA":
		return "Ulatech"
	case "PST":
		return "Primas"
	case "OPT":
		return "Opus"
	case "SUR":
		return "Suretly"
	case "LRC":
		return "Loopring"
	case "LTCU":
		return "LiteCoin Ultra"
	case "POE":
		return "Po.et"
	case "NTO":
		return "Fujinto"
	case "STRC":
		return "StarCredits"
	case "KRONE":
		return "Kronecoin"
	case "CYDER":
		return "Cyder"
	case "MTNC":
		return "Masternodecoin"
	case "MTH":
		return "Monetha"
	case "AVT":
		return "Aventus"
	case "DLT":
		return "Agrello"
	case "HVN":
		return "Hive Project"
	case "VSX":
		return "Vsync"
	case "MAGN":
		return "Magnetcoin"
	case "MDA":
		return "Moeda Loyalty Points"
	case "NEBL":
		return "Neblio"
	case "VIVO":
		return "VIVO"
	case "TRX":
		return "TRON"
	case "OCL":
		return "Oceanlab"
	case "REX":
		return "imbrex"
	case "BUZZ":
		return "BuzzCoin"
	case "CREDO":
		return "Credo"
	case "DRXNE":
		return "DROXNE"
	case "AHT":
		return "Bowhead"
	case "MANA":
		return "Decentraland"
	case "IND":
		return "Indorse Token"
	case "XPA":
		return "XPA"
	case "SCL":
		return "Sociall"
	case "ATB":
		return "ATBCoin"
	case "IQT":
		return "iQuant"
	case "ETHD":
		return "Ethereum Dark"
	case "PRO":
		return "Propy"
	case "LINK":
		return "ChainLink"
	case "BMC":
		return "Blackmoon"
	case "WIC":
		return "Wi Coin"
	case "ELIX":
		return "Elixir"
	case "XBL":
		return "Billionaire Token"
	case "VIBE":
		return "VIBE"
	case "SUB":
		return "Substratum"
	case "DAY":
		return "Chronologic"
	case "CHIPS":
		return "CHIPS"
	case "TKR":
		return "CryptoInsight"
	case "PIX":
		return "Lampix"
	case "COSS":
		return "COSS"
	case "CSNO":
		return "BitDice"
	case "RVT":
		return "Rivetz"
	case "KIN":
		return "Kin"
	case "ITZ":
		return "Interzone"
	case "TGT":
		return "Target Coin"
	case "SALT":
		return "SALT"
	case "ORME":
		return "Ormeus Coin"
	case "KLN":
		return "Kolion"
	case "MCI":
		return "Musiconomi"
	case "COLX":
		return "ColossusXT"
	case "TZC":
		return "TrezarCoin"
	case "HDLB":
		return "HODL Bucks"
	case "ODN":
		return "Obsidian"
	case "COB":
		return "Cobinhood"
	case "REC":
		return "Regalcoin"
	case "MSD":
		return "MSD"
	case "BIS":
		return "Bismuth"
	case "ADA":
		return "Cardano"
	case "XTZ":
		return "Tezos"
	case "VOISE":
		return "Voise"
	case "XIN":
		return "Infinity Economics"
	case "ATM":
		return "ATMChain"
	case "KICK":
		return "KickCoin"
	case "VIB":
		return "Viberate"
	case "RHOC":
		return "RChain"
	case "INXT":
		return "Internxt"
	case "WHL":
		return "WhaleCoin"
	case "FLIK":
		return "FLiK"
	case "EBET":
		return "EthBet"
	case "CNX":
		return "Cryptonex"
	case "WILD":
		return "Wild Crypto"
	case "REAL":
		return "REAL"
	case "HBT":
		return "Hubii Network"
	case "CCT":
		return "Crystal Clear "
	case "BCO":
		return "BridgeCoin"
	case "EVX":
		return "Everex"
	case "PPP":
		return "PayPie"
	case "AIR":
		return "AirToken"
	case "POS":
		return "PoSToken"
	case "SDRN":
		return "Senderon"
	case "ALIS":
		return "ALIS"
	case "BTCZ":
		return "BitcoinZ"
	case "HGT":
		return "HelloGold"
	case "CND":
		return "Cindicator"
	case "ENG":
		return "Enigma"
	case "CTIC3":
		return "Coimatic 3.0"
	case "BSN":
		return "Bastonet"
	case "ZSC":
		return "Zeusshield"
	case "ECASH":
		return "Ethereum Cash"
	case "COR":
		return "CORION"
	case "SIC":
		return "Swisscoin"
	case "ATS":
		return "Authorship"
	case "RKC":
		return "Royal Kingdom Coin"
	case "AKY":
		return "Akuya Coin"
	case "EXN":
		return "ExchangeN"
	case "PIPL":
		return "PiplCoin"
	case "EDO":
		return "Eidoo"
	case "AST":
		return "AirSwap"
	case "BSR":
		return "BitSoar"
	case "CAG":
		return "Change"
	case "BCPT":
		return "BlockMason Credit Protocol"
	case "AION":
		return "Aion"
	case "TRCT":
		return "Tracto"
	case "ART":
		return "Maecenas"
	case "XGOX":
		return "XGOX"
	case "EVR":
		return "Everus"
	case "DUTCH":
		return "Dutch Coin"
	case "OTN":
		return "Open Trading Network"
	case "DRT":
		return "DomRaider"
	case "REQ":
		return "Request Network"
	case "B2X":
		return "SegWit2x"
	case "ETG":
		return "Ethereum Gold"
	case "BLUE":
		return "Blue Protocol"
	case "RUNNERS":
		return "Runners"
	case "LIFE":
		return "LIFE"
	case "HDG":
		return "Hedge"
	case "MOD":
		return "Modum"
	case "AMB":
		return "Ambrosus"
	case "ICOS":
		return "ICOS"
	case "KCS":
		return "KuCoin Shares"
	case "EXRN":
		return "EXRNchain"
	case "POLL":
		return "ClearPoll"
	case "LA":
		return "LATOKEN"
	case "XUC":
		return "Exchange Union"
	case "NULS":
		return "Nuls"
	case "BTCRED":
		return "Bitcoin Red"
	case "PRG":
		return "Paragon"
	case "BOS":
		return "BOScoin"
	case "GMT":
		return "Mercury Protocol"
	case "ICX":
		return "ICON"
	case "JS":
		return "JavaScript Token"
	case "ELITE":
		return "Ethereum Lite"
	case "ITT":
		return "Intelligent Trading Foundation"
	case "IETH":
		return "iEthereum"
	case "PIRL":
		return "Pirl"
	case "XNN":
		return "Xenon"
	case "LUX":
		return "LUXCoin"
	case "NTWK":
		return "Network Token"
	case "DOVU":
		return "Dovu"
	case "RPX":
		return "Red Pulse"
	case "BT2":
		return "BT2 CST"
	case "PLACO":
		return "PlayerCoin"
	case "ROOFS":
		return "Roofs"
	case "FAP":
		return "FAPcoin"
	case "BTCM":
		return "BTCMoon"
	case "FUEL":
		return "Etherparty"
	case "ELLA":
		return "Ellaism"
	case "VULC":
		return "Vulcano"
	case "QVT":
		return "Qvolta"
	case "RMC":
		return "Russian Miner Coin"
	case "FYP":
		return "FlypMe"
	case "EBTC":
		return "eBitcoin"
	case "BTBc":
		return "Bitbase"
	case "ENJ":
		return "Enjin Coin"
	case "POWR":
		return "Power Ledger"
	case "GRID":
		return "Grid+"
	case "R":
		return "Revain"
	case "ATL":
		return "ATLANT"
	case "ETN":
		return "Electroneum"
	case "HIGH":
		return "High Gain"
	case "MNX":
		return "MinexCoin"
	case "FOR":
		return "FORCE"
	case "DATA":
		return "Streamr DATAcoin"
	case "XSH":
		return "SHIELD"
	case "PURE":
		return "Pure"
	case "ELTCOIN":
		return "ELTCOIN"
	case "DSR":
		return "Desire"
	case "UKG":
		return "Unikoin Gold"
	case "CRDNC":
		return "Credence Coin"
	case "NIO":
		return "Autonio"
	case "CTX":
		return "CarTaxi Token"
	case "ARN":
		return "Aeron"
	case "STARS":
		return "StarCash Network"
	case "PHR":
		return "Phore"
	case "FRD":
		return "Farad"
	case "INN":
		return "Innova"
	case "RDN":
		return "Raiden Network Token"
	case "DPY":
		return "Delphy"
	case "ZEPH":
		return "Zephyr"
	case "ERC20":
		return "ERC20"
	case "TIE":
		return "Ties.DB"
	case "BPL":
		return "Blockpool"
	case "GRIM":
		return "Grimcoin"
	case "OXY":
		return "Oxycoin"
	case "EPY":
		return "Emphy"
	case "HOLD":
		return "Stellar Holdings"
	case "NEOG":
		return "NEO GOLD"
	case "DBET":
		return "DecentBet"
	case "HST":
		return "Decision Token"
	case "SSS":
		return "Sharechain"
	case "UFR":
		return "Upfiring"
	case "HAT":
		return "Hat.Exchange"
	case "STU":
		return "bitJob"
	case "GVT":
		return "Genesis Vision"
	case "EAGLE":
		return "EagleCoin"
	case "EAG":
		return "EA Coin"
	case "PRIX":
		return "Privatix"
	case "ITNS":
		return "IntenseCoin"
	case "EBCH":
		return "EBCH"
	case "SISA":
		return "SISA"
	case "ASTRO":
		return "Astro"
	case "PAYX":
		return "Paypex"
	case "GRX":
		return "GOLD Reward Token"
	case "AERM":
		return "Aerium"
	case "BTE":
		return "BitSerial"
	case "SGR":
		return "Sugar Exchange"
	case "VIU":
		return "Viuly"
	case "ALQO":
		return "ALQO"
	case "GBX":
		return "GoByte"
	case "WC":
		return "WINCOIN"
	case "PRL":
		return "Oyster"
	case "B2B":
		return "B2BX"
	case "PNX":
		return "Phantomx"
	case "DGPT":
		return "DigiPulse"
	case "DNA":
		return "EncrypGen"
	case "INK":
		return "Ink"
	case "BOT":
		return "Bodhi"
	case "QSP":
		return "Quantstamp"
	case "QASH":
		return "QASH"
	case "ZZC":
		return "ZoZoCoin"
	case "TSL":
		return "Energo"
	case "PBL":
		return "Publica"
	case "MAG":
		return "Magnet"
	case "SPANK":
		return "SpankChain"
	case "VOT":
		return "VoteCoin"
	case "BCD":
		return "Bitcoin Diamond"
	case "VEE":
		return "BLOCKv"
	case "AI":
		return "POLY AI"
	case "PLX":
		return "PlexCoin"
	case "DIVX":
		return "Divi"
	case "MONK":
		return "Monkey Project"
	case "FLIXX":
		return "Flixxo"
	case "GLS":
		return "GlassCoin"
	case "TNB":
		return "Time New Bank"
	case "WISH":
		return "MyWish"
	case "EVC":
		return "EventChain"
	case "LEND":
		return "ETHLend"
	case "ONG":
		return "onG.social"
	case "CCO":
		return "Ccore"
	case "DRGN":
		return "Dragonchain"
	case "PFR":
		return "Payfair"
	case "PRE":
		return "Presearch"
	case "BCDN":
		return "BlockCDN"
	case "CAPP":
		return "Cappasity"
	case "ERO":
		return "Eroscoin"
	case "MAGE":
		return "MagicCoin"
	case "ITC":
		return "IoT Chain"
	case "JIYO":
		return "Jiyo"
	case "SEND":
		return "Social Send"
	case "BON":
		return "Bonpay"
	case "NUKO":
		return "Nekonium"
	case "SNOV":
		return "Snovio"
	case "SBC":
		return "StrikeBitClub"
	case "BWK":
		return "Bulwark"
	case "SAGA":
		return "SagaCoin"
	case "CMS":
		return "COMSA ETH"
	case "KBR":
		return "Kubera Coin"
	case "TOK":
		return "Tokugawa"
	case "PCOIN":
		return "Pioneer Coin"
	case "WABI":
		return "WaBi"
	case "CRC":
		return "CrowdCoin"
	case "WAND":
		return "WandX"
	case "SPF":
		return "SportyCo"
	case "CRED":
		return "Verify"
	case "SCT":
		return "Soma"
	case "UQC":
		return "Uquid Coin"
	case "MDS":
		return "MediShares"
	case "PRA":
		return "ProChain"
	case "IGNIS":
		return "Ignis"
	case "SMT":
		return "SmartMesh"
	case "HWC":
		return "HollyWoodCoin"
	case "PKT":
		return "Playkey"
	case "FIL":
		return "Filecoin Futures"
	case "BCX":
		return "BitcoinX"
	case "SBTC":
		return "Super Bitcoin"
	case "DAT":
		return "Datum"
	case "TRDT":
		return "Trident Group"
	case "BTCA":
		return "Bitair"
	case "AMM":
		return "MicroMoney"
	case "LOC":
		return "LockTrip"
	case "WRC":
		return "Worldcore"
	case "GTO":
		return "Gifto"
	case "YTN":
		return "YENTEN"
	case "GNX":
		return "Genaro Network"
	case "UBTC":
		return "United Bitcoin"
	case "STAR":
		return "Starbase"
	case "OST":
		return "OST"
	case "STORM":
		return "Storm"
	case "DTR":
		return "Dynamic Trading Rights"
	case "ELF":
		return "aelf"
	case "WAX":
		return "WAX"
	case "MED":
		return "MediBloc QRC20"
	case "DEW":
		return "DEW"
	case "NGC":
		return "NAGA"
	case "BRD":
		return "Bread"
	case "BIX":
		return "Bibox Token"
	case "DAI":
		return "Dai"
	case "SPHTX":
		return "SophiaTX"
	case "BNTY":
		return "Bounty0x"
	case "ACE":
		return "Ace"
	case "DIM":
		return "DIMCOIN"
	case "SRN":
		return "SIRIN LABS Token"
	case "CPAY":
		return "Cryptopay"
	case "HTML":
		return "HTMLCOIN"
	case "DBC":
		return "DeepBrain Chain"
	case "HBC":
		return "HomeBlockCoin"
	case "NEU":
		return "Neumark"
	case "UTK":
		return "UTRUST"
	case "QLC":
		return "QLINK"
	case "PLAY":
		return "HEROcoin"
	case "BIG":
		return "BigONE Token"
	case "MTX":
		return "Matryx"
	case "MOT":
		return "Olympus Labs"
	case "HPY":
		return "Hyper Pay"
	case "PYLNT":
		return "Pylon Network"
	case "STAK":
		return "STRAKS"
	case "FDX":
		return "FidentiaX"
	case "TAU":
		return "Lamden"
	case "ESC":
		return "Escroco"
	case "BLT":
		return "Bloom"
	case "SWFTC":
		return "SwftCoin"
	case "COV":
		return "Covesting"
	case "CAN":
		return "CanYaCoin"
	case "APPC":
		return "AppCoins"
	case "HPB":
		return "High Performance Blockchain"
	case "WICC":
		return "WaykiChain"
	case "NUMUS":
		return "NumusCash"
	case "MDT":
		return "Measurable Data Token"
	case "GCS":
		return "GameChain System"
	case "NMS":
		return "Numus"
	case "CL":
		return "Coinlancer"
	case "CEFS":
		return "CryptopiaFeeShares"
	case "GET":
		return "GET Protocol"
	case "OPC":
		return "OP Coin"
	case "CFUN":
		return "CFun"
	case "AIDOC":
		return "AI Doctor"
	case "POLIS":
		return "Polis"
	case "HKN":
		return "Hacken"
	case "SHOW":
		return "Show"
	case "STN":
		return "Steneum Coin"
	case "ZAP":
		return "Zap"
	case "TCT":
		return "TokenClub"
	case "AIX":
		return "Aigang"
	case "REBL":
		return "REBL"
	case "INS":
		return "INS Ecosystem"
	case "GOD":
		return "Bitcoin God"
	case "UTT":
		return "United Traders Token"
	case "CDX":
		return "Commodity Ad Network"
	case "TIO":
		return "Trade Token"
	case "BDG":
		return "BitDegree"
	case "QUN":
		return "QunQun"
	case "TOPC":
		return "TopChain"
	case "LEV":
		return "Leverj"
	case "KRM":
		return "Karma"
	case "KCASH":
		return "Kcash"
	case "ATN":
		return "ATN"
	case "SXDT":
		return "Spectre.ai Dividend Token"
	case "SXUT":
		return "Spectre.ai Utility Token"
	case "SWTC":
		return "Jingtum Tech"
	case "VZT":
		return "Vezt"
	case "CLD":
		return "Cloud"
	case "UCOM":
		return "United Crypto Community"
	case "BCA":
		return "Bitcoin Atom"
	case "UGC":
		return "ugChain"
	case "BKX":
		return "Bankex"
	case "EKO":
		return "EchoLink"
	case "BTO":
		return "Bottos"
	case "TEL":
		return "Telcoin"
	case "IC":
		return "Ignition"
	case "WETH":
		return "WETH"
	case "HAC":
		return "Hackspace Capital"
	case "KEY":
		return "Selfkey"
	case "INT":
		return "Internet Node Token"
	case "RNT":
		return "OneRoot Network"
	case "SENSE":
		return "Sense"
	case "MOAC":
		return "MOAC"
	case "TOKC":
		return "TOKYO"
	case "IOST":
		return "IOST"
	case "IDT":
		return "InvestDigital"
	case "AIT":
		return "AICHAIN"
	case "QUBE":
		return "Qube"
	case "EDT":
		return "EtherDelta Token"
	case "SPC":
		return "SpaceChain"
	case "ORE":
		return "Galactrum"
	case "HC":
		return "Harvest Masternode Coin"
	case "HORSE":
		return "Ethorse"
	case "RCT":
		return "RealChain"
	case "ARCT":
		return "ArbitrageCT"
	case "THETA":
		return "Theta Token"
	case "MVC":
		return "Maverick Chain"
	case "NOX":
		return "Nitro"
	case "IPL":
		return "InsurePal"
	case "IDXM":
		return "IDEX Membership"
	case "AURA":
		return "Aurora DAO"
	case "AGI":
		return "SingularityNET"
	case "GAT":
		return "Gatcoin"
	case "SEXC":
		return "ShareX"
	case "CHAT":
		return "ChatCoin"
	case "DDD":
		return "Scry.info"
	case "MOBI":
		return "Mobius"
	case "HOT":
		return "Hydro Protocol"
	case "STC":
		return "StarChain"
	case "IPC":
		return "IPChain"
	case "LIGHT":
		return "LightChain"
	case "REF":
		return "RefToken"
	case "YEE":
		return "YEE"
	case "AAC":
		return "Acute Angle Cloud"
	case "SSC":
		return "SelfSell"
	case "READ":
		return "Read"
	case "MOF":
		return "Molecular Future"
	case "TNC":
		return "Trinity Network Credit"
	case "C20":
		return "CRYPTO20"
	case "ARY":
		return "Block Array"
	case "DTA":
		return "DATA"
	case "CRPT":
		return "Crypterium"
	case "SPK":
		return "Sparks"
	case "CV":
		return "carVertical"
	case "TBX":
		return "Tokenbox"
	case "EKT":
		return "EDUCare"
	case "UIP":
		return "UnlimitedIP"
	case "PRS":
		return "PressOne"
	case "OF":
		return "OFCOIN"
	case "TRUE":
		return "True Chain"
	case "OCN":
		return "Odyssey"
	case "IDH":
		return "indaHash"
	case "QBIC":
		return "Qbic"
	case "GUESS":
		return "Peerguess"
	case "AID":
		return "AidCoin"
	case "EVE":
		return "Devery"
	case "BPT":
		return "Blockport"
	case "AXP":
		return "aXpire"
	case "TRAC":
		return "OriginTrail"
	case "LET":
		return "LinkEye"
	case "ZIL":
		return "Zilliqa"
	case "MEET":
		return "CoinMeet"
	case "SLT":
		return "Smartlands"
	case "FOTA":
		return "Fortuna"
	case "SOC":
		return "All Sports"
	case "MAN":
		return "Matrix AI Network"
	case "GRLC":
		return "Garlicoin"
	case "RUFF":
		return "Ruff"
	case "NKC":
		return "Nework"
	case "COFI":
		return "CoinFi"
	case "EQL":
		return "Equal"
	case "HLC":
		return "HalalChain"
	case "ZPT":
		return "Zeepin"
	case "OC":
		return "OceanChain"
	case "CANDY":
		return "Candy"
	case "SMS":
		return "Speed Mining Service"
	case "EPC":
		return "Electronic PK Chain"
	case "VLC":
		return "ValueChain"
	case "BTW":
		return "BitWhite"
	case "CXO":
		return "CargoX"
	case "TRF":
		return "Travelflex"
	case "ELA":
		return "Elastos"
	case "STK":
		return "STK"
	case "PARETO":
		return "Pareto Network"
	case "POLY":
		return "Polymath"
	case "MTN":
		return "Medicalchain"
	case "JNT":
		return "Jibrel Network"
	case "CHSB":
		return "SwissBorg"
	case "ZLA":
		return "Zilla"
	case "ADB":
		return "adbank"
	case "HT":
		return "Huobi Token"
	case "DMT":
		return "DMarket"
	case "ING":
		return "Iungo"
	case "SWM":
		return "Swarm"
	case "TKY":
		return "THEKEY"
	case "DRPU":
		return "DCORP Utility"
	case "ESZ":
		return "EtherSportz"
	case "DXT":
		return "Datawallet"
	case "WPR":
		return "WePower"
	case "UCASH":
		return "U.CASH"
	case "MNTP":
		return "GoldMint"
	case "JEW":
		return "Shekel"
	case "MLM":
		return "MktCoin"
	case "AVH":
		return "Animation Vision Cash"
	case "LOCI":
		return "LOCIcoin"
	case "INDI":
		return "Indicoin"
	case "JC":
		return "Jesus Coin"
	case "BIO":
		return "BioCoin"
	case "SUP":
		return "Superior Coin"
	case "TIG":
		return "Tigereum"
	case "UTNP":
		return "Universa"
	case "ACAT":
		return "Alphacat"
	case "EVN":
		return "Envion"
	case "RMT":
		return "SureRemit"
	case "DTH":
		return "Dether"
	case "CAS":
		return "Cashaa"
	case "FSN":
		return "Fusion"
	case "W3C":
		return "W3Coin"
	case "ECH":
		return "Etherecash"
	case "MWAT":
		return "Restart Energy MWAT"
	case "GLA":
		return "Gladius Token"
	case "DADI":
		return "DADI"
	case "NTK":
		return "Neurotoken"
	case "GEM":
		return "Gems "
	case "NEC":
		return "Nectar"
	case "REN":
		return "Republic Protocol"
	case "LCC":
		return "Litecoin Cash"
	case "STQ":
		return "Storiqa"
	case "TDX":
		return "Tidex Token"
	case "CPY":
		return "COPYTRACK"
	case "NCASH":
		return "Nucleus Vision"
	case "ABT":
		return "Arcblock"
	case "REM":
		return "Remme"
	case "EXY":
		return "Experty"
	case "POA":
		return "POA Network"
	case "XNK":
		return "Ink Protocol"
	case "RKT":
		return "Rock"
	case "BEZ":
		return "Bezop"
	case "IHT":
		return "IHT Real Estate Protocol"
	case "RFR":
		return "Refereum"
	case "LYM":
		return "Lympo"
	case "SETH":
		return "Sether"
	case "CS":
		return "Credits"
	case "BEE":
		return "Bee Token"
	case "INSTAR":
		return "Insights Network"
	case "AUTO":
		return "Cube"
	case "EZT":
		return "EZToken"
	case "TUBE":
		return "BitTube"
	case "LEDU":
		return "Education Ecosystem"
	case "TUSD":
		return "TrueUSD"
	case "HQX":
		return "HOQU"
	case "STAC":
		return "StarterCoin"
	case "ONT":
		return "Ontology"
	case "DATX":
		return "DATx"
	case "J8T":
		return "JET8"
	case "CHP":
		return "CoinPoker"
	case "TOMO":
		return "TomoChain"
	case "GRFT":
		return "Graft"
	case "BAX":
		return "BABB"
	case "ELEC":
		return "Electrify.Asia"
	case "BTCP":
		return "Bitcoin Private"
	case "TEN":
		return "Tokenomy"
	case "RVN":
		return "Ravencoin"
	case "TFD":
		return "TE-FOOD"
	case "SHIP":
		return "ShipChain"
	case "LDC":
		return "Leadcoin"
	case "SHP":
		return "Sharpe Platform Token"
	case "LALA":
		return "LALA World"
	case "OCC":
		return "Octoin Coin"
	case "DEB":
		return "Debitum"
	case "CENNZ":
		return "Centrality"
	case "HAV":
		return "Havven"
	case "FLUZ":
		return "Fluz Fluz"
	case "LOOM":
		return "Loom Network"
	case "GETX":
		return "Guaranteed Ethurance Token Extra"
	case "HIRE":
		return "HireMatch"
	case "DROP":
		return "Dropil"
	case "BANCA":
		return "Banca"
	case "DRG":
		return "Dragon Coins"
	case "LATX":
		return "LatiumX"
	case "NANJ":
		return "NANJCOIN"
	case "CKUSD":
		return "CK USD"
	case "UP":
		return "UpToken"
	case "BBN":
		return "Banyan Network"
	case "NOAH":
		return "Noah Coin"
	case "LGO":
		return "LGO Exchange"
	case "1WO":
		return "1World"
	case "NPX":
		return "NaPoleonX"
	case "NPXS":
		return "Pundi X"
	case "BITG":
		return "Bitcoin Green"
	case "BFT":
		return "BnkToTheFuture"
	case "WAN":
		return "Wanchain"
	case "AMLT":
		return "AMLT"
	case "MITH":
		return "Mithril"
	case "LST":
		return "Lendroid Support Token"
	case "PCL":
		return "Peculium"
	case "SIG":
		return "Spectiv"
	case "RNTB":
		return "BitRent"
	case "XBP":
		return "BlitzPredict"
	case "LNC":
		return "Blocklancer"
	case "SPD":
		return "Stipend"
	case "IPSX":
		return "IP Exchange"
	case "SCC":
		return "StockChain"
	case "BSTN":
		return "BitStation"
	case "SWTH":
		return "Switcheo"
	case "SEN":
		return "Consensus"
	case "SENC":
		return "Sentinel Chain"
	case "VIT":
		return "Vice Industry Token"
	case "FDZ":
		return "Friendz"
	case "TPAY":
		return "TokenPay"
	case "BERRY":
		return "Rentberry"
	case "XTL":
		return "Stellite"
	case "NCT":
		return "PolySwarm"
	case "ODE":
		return "ODEM"
	case "XMO":
		return "Monero Original"
	case "XSN":
		return "Stakenet"
	case "XDCE":
		return "XinFin Network"
	case "TDS":
		return "TokenDesk"
	case "BBI":
		return "BelugaPay"
	case "FID":
		return "Fidelium"
	case "CTXC":
		return "Cortex"
	case "ATC":
		return "Arbitracoin"
	case "WIN":
		return "WCOIN"
	case "CPX":
		return "Apex"
	case "CVT":
		return "CyberVein"
	case "SENT":
		return "Sentinel"
	case "EOSDAC":
		return "eosDAC"
	case "UUU":
		return "U Network"
	case "ADH":
		return "AdHive"
	case "SNIP":
		return "SnipCoin"
	case "BSM":
		return "Bitsum"
	case "DEV":
		return "DeviantCoin"
	case "CBT":
		return "CommerceBlock"
	case "GRMD":
		return "GreenMed"
	case "CVH":
		return "Curriculum Vitae"
	case "AUC":
		return "Auctus"
	case "BUBO":
		return "Budbo"
	case "XMC":
		return "Monero Classic"
	case "DAN":
		return "Daneel"
	case "BRM":
		return "BrahmaOS"
	case "MFG":
		return "SyncFab"
	case "DIG":
		return "Dignity"
	case "ADI":
		return "Aditus"
	case "TRIO":
		return "Tripio"
	case "XHV":
		return "Haven Protocol"
	case "KST":
		return "StarCoin"
	case "DERO":
		return "Dero"
	case "EFX":
		return "Effect.AI"
	case "FTX":
		return "FintruX Network"
	case "EARTH":
		return "Earth Token"
	case "MRK":
		return "MARK.SPACE"
	case "CROP":
		return "Cropcoin"
	case "SRCOIN":
		return "SRCOIN"
	case "CHX":
		return "Chainium"
	case "MSR":
		return "Masari"
	case "DOCK":
		return "Dock"
	case "PHI":
		return "PHI Token"
	case "BBC":
		return "TraDove B2BCoin"
	case "DML":
		return "Decentralized Machine Learning"
	case "HBZ":
		return "Helbiz"
	case "ORI":
		return "Origami"
	case "TRAK":
		return "TrakInvest"
	case "APH":
		return "Aphelion"
	case "ZCO":
		return "Zebi"
	case "LND":
		return "Lendingblock"
	case "XES":
		return "Proxeus"
	case "VIPS":
		return "Vipstar Coin"
	case "RBLX":
		return "Rublix"
	case "BTRN":
		return "Biotron"
	case "PNT":
		return "Penta"
	case "NBAI":
		return "Nebula AI"
	case "LRN":
		return "Loopring NEO"
	case "NEXO":
		return "Nexo"
	case "VME":
		return "VeriME"
	case "DAX":
		return "DAEX"
	case "HYDRO":
		return "Hydro"
	case "SS":
		return "Sharder"
	case "TTT":
		return "TrustNote"
	case "BCI":
		return "Bitcoin Interest"
	case "BETR":
		return "BetterBetting"
	case "TNS":
		return "Transcodium"
	case "AMN":
		return "Amon"
	case "PLAN":
		return "Plancoin"
	case "FLP":
		return "FLIP"
	case "CMCT":
		return "Crowd Machine"
	case "MITX":
		return "Morpheus Labs"
	case "LIVE":
		return "Live Stars"
	case "MTC":
		return "Docademic"
	case "MT":
		return "MyToken"
	case "NTY":
		return "Nexty"
	case "CJT":
		return "ConnectJob"
	case "BOUTS":
		return "BoutsPro"
	case "PAL":
		return "PolicyPal Network"
	case "CRE":
		return "Cybereits"
	case "GENE":
		return "Parkgene"
	case "APR":
		return "APR Coin"
	case "AC3":
		return "AC3"
	case "FXT":
		return "FuzeX"
	case "ZIPT":
		return "Zippie"
	case "SKM":
		return "Skrumble Network"
	case "GEN":
		return "DAOstack"
	case "BZNT":
		return "Bezant"
	case "TEAM":
		return "TokenStars"
	case "FRV":
		return "Fitrova"
	case "OOT":
		return "Utrum"
	case "FREC":
		return "Freyrchain"
	case "EDU":
		return "EduCoin"
	case "CNN":
		return "Content Neutrality Network"
	case "INSUR":
		return "InsurChain"
	case "GSC":
		return "Global Social Chain"
	case "SGCC":
		return "Super Game Chain"
	case "DGX":
		return "Digix Gold Token"
	case "INC":
		return "Influence Chain"
	case "IIC":
		return "Intelligent Investment Chain"
	case "SKB":
		return "Sakura Bloom"
	case "BANK":
		return "Bank Coin"
	case "NPER":
		return "NPER"
	case "DASC":
		return "Dascoin"
	case "BMH":
		return "BlockMesh"
	case "LOKI":
		return "Loki"
	case "SGN":
		return "Signals Network"
	case "SHL":
		return "Oyster Shell"
	case "FND":
		return "FundRequest"
	case "DTRC":
		return "Datarius Credit"
	case "CLN":
		return "Colu Local Network"
	case "HER":
		return "HeroNode"
	case "TKA":
		return "Tokia"
	case "CLO":
		return "Callisto Network"
	case "UBT":
		return "Unibright"
	case "PAT":
		return "Patron"
	case "LBA":
		return "Libra Credit"
	case "LWF":
		return "Local World Forwarders"
	case "OPEN":
		return "Open Platform"
	case "MORPH":
		return "Morpheus Network"
	case "SNTR":
		return "Silent Notary"
	case "XYO":
		return "XYO Network"
	case "CPT":
		return "Cryptaur"
	case "APIS":
		return "APIS"
	case "FT":
		return "Fabric Token"
	case "XRH":
		return "Rhenium"
	case "CAZ":
		return "Cazcoin"
	case "DGTX":
		return "Digitex Futures"
	case "GIN":
		return "GINcoin"
	case "INV":
		return "Invacio"
	case "FACE":
		return "Faceter"
	case "AVA":
		return "Travala"
	case "IOTX":
		return "IoTeX"
	case "EXC":
		return "Eximchain"
	case "LUC":
		return "Level Up Coin"
	case "NKN":
		return "NKN"
	case "NAVI":
		return "Naviaddress"
	case "ZIP":
		return "ZIP"
	case "SOUL":
		return "Phantasma"
	case "REPO":
		return "REPO"
	case "SEELE":
		return "Seele"
	case "EJOY":
		return "EJOY"
	case "IVY":
		return "Ivy"
	case "CNET":
		return "ContractNet"
	case "BBO":
		return "Bigbom"
	case "0xBTC":
		return "0xBitcoin"
	case "PAI":
		return "PCHAIN"
	case "QKC":
		return "QuarkChain"
	case "LYL":
		return "LoyalCoin"
	case "BNK":
		return "Bankera"
	case "ETZ":
		return "Ether Zero"
	case "OMX":
		return "Shivom"
	case "MEDX":
		return "MediBloc ERC20"
	case "FTO":
		return "FuturoCoin"
	case "ABYSS":
		return "The Abyss"
	case "PMNT":
		return "Paymon"
	case "HUR":
		return "Hurify"
	case "TMT":
		return "TRAXIA"
	case "EGCC":
		return "Engine"
	case "MRQ":
		return "MIRQ"
	case "PKC":
		return "PikcioChain"
	case "CBC":
		return "CashBet Coin"
	case "CEEK":
		return "CEEK VR"
	case "SAL":
		return "SalPay"
	case "COU":
		return "Couchain"
	case "XMX":
		return "XMax"
	case "GO":
		return "GoChain"
	case "SSP":
		return "Smartshare"
	case "UPP":
		return "Sentinel Protocol"
	case "BWT":
		return "Bittwatt"
	case "DAG":
		return "Constellation"
	case "MVP":
		return "Merculet"
	case "FGC":
		return "FantasyGold"
	case "ETK":
		return "EnergiToken"
	case "MET":
		return "Metronome"
	case "AOA":
		return "Aurora"
	case "ALX":
		return "ALAX"
	case "TERN":
		return "Ternio"
	case "BOE":
		return "Bodhi ETH"
	case "ORS":
		return "Origin Sport"
	case "RTE":
		return "Rate3"
	case "DCC":
		return "Distributed Credit Chain"
	case "ZCN":
		return "0chain"
	case "ZINC":
		return "ZINC"
	case "FSBT":
		return "Forty Seven Bank"
	case "EGT":
		return "Egretia"
	case "TTU":
		return "TaTaTu"
	case "DOR":
		return "Dorado"
	case "CAR":
		return "CarBlock"
	case "BOB":
		return "Bob's Repair"
	case "KNDC":
		return "KanadeCoin"
	case "CARD":
		return "Cardstack"
	case "WWB":
		return "Wowbit"
	case "ONL":
		return "On.Live"
	case "OTB":
		return "OTCBTC Token"
	case "CONI":
		return "Coni"
	case "MFT":
		return "Mainframe"
	case "CCCX":
		return "Clipper Coin"
	case "GOT":
		return "GoNetwork"
	case "THRT":
		return "Thrive Token"
	case "FTI":
		return "FansTime"
	case "PCH":
		return "POPCHAIN"
	case "SEER":
		return "SEER"
	case "ESS":
		return "Essentia"
	case "KBC":
		return "Karatgold Coin"
	case "HSC":
		return "HashCoin"
	case "LIKE":
		return "LikeCoin"
	case "YUP":
		return "Crowdholding"
	case "XSG":
		return "SnowGem"
	case "DTX":
		return "DaTa eXchange"
	case "BKBT":
		return "BeeKan"
	case "MOC":
		return "Mossland"
	case "SFU":
		return "Saifu"
	case "BZ":
		return "Bit-Z Token"
	case "DWS":
		return "DWS"
	case "ZXC":
		return "0xcert"
	case "OLT":
		return "OneLedger"
	case "ATMI":
		return "Atonomi"
	default:
		return symbol
	}
}
