# docker stack deploy -c docker-compose.yml blockchain-scrapers
version: '3.2'

services:
  bitcoind:
    image:
      kylemanna/bitcoind
    ports:
      - "8332"
    volumes:
      - $HOME/srv/bitcoin:/bitcoin
    command: btc_oneshot -printtoconsole -prune=550 -rpcallowip=::/0 -disablewallet -rpcpassword=mysecretrpcdiapassword -rpcuser=mysecretrpcdiauser
    logging:
      options:
        max-size: "50m"
    networks:
      - scrapers-network
    deploy:
      mode: global
      restart_policy:
        delay: 2s
        window: 20s
  litecoind:
    image:
      uphold/litecoin-core
    ports:
      - "9332"
    volumes:
      - /home/srv/litecoin:/var/lib/litecoin
    command: -printtoconsole -prune=550 -rpcallowip=::/0 -disablewallet -rpcuser=mysecretrpcdiauser -rpcpassword=njTcaNX74sSf46_TXacMVlyPMJjuv9i03bqBgj9KQ8E=

    environment:
      - LITECOIN_DATA=/var/lib/litecoin
    logging:
      options:
        max-size: "50m"
    networks:
      - scrapers-network
    deploy:
      mode: global
      restart_policy:
        delay: 2s
        window: 20s
  geth:
    image:
      ethereum/client-go:alpine
    ports:
      - "8545"
      - "30303"
    volumes:
      - /home/srv/geth:/root/.ethereum
    command: --rpcvhosts geth --rpc --rpcaddr "0.0.0.0" --syncmode "light" --cache 1024 --rpc

    logging:
      options:
        max-size: "50m"
    networks:
      - scrapers-network
    deploy:
      mode: global
      restart_policy:
        delay: 2s
        window: 20s
  cardano:
    image:
      diadata/cardano-explorer-docker
    ports:
      - "8100"
    volumes:
      - /home/srv/cardano:/home/cardano/cardano-sl/state-explorer-mainnet
    logging:
      options:
        max-size: "50m"
    networks:
      - scrapers-network
    deploy:
      mode: global
      restart_policy:
        delay: 2s
        window: 20s
  neonode:
    image:
      bountyjs/neocli-mainnet
    ports:
      - "10332:10332"
    volumes:
      - /home/srv/neo:/app/Chain_00746E41
    tty: true
    logging:
      options:
        max-size: "50m"
    networks:
      - scrapers-network
    deploy:
      mode: global
      restart_policy:
        delay: 2s
        window: 20s
        
  monero:
    image:
      ${DOCKER_HUB_LOGIN}/blockchain-scrapers_monero
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/api-golang/blockchain-scrapers/blockchains/monero/node/Dockerfile-monero
    ports:
      - "18080"
      - "18081"
    volumes:
      - /home/srv/monero:/root/.bitmonero
    networks:
      - scrapers-network
      
  bitcoin-cash:
    image:
      uphold/bitcoin-abc
    ports:
      - "8332"
    volumes:
      - /home/srv/bitcoin-cash:/var/lib/bitcoin-cash
    command: -printtoconsole -prune=550 -rpcallowip=::/0 -disablewallet -rpcuser=mysecretrpcdiauser -rpcpassword=njTcaNX74sSf46_TXacMVlyPMJjuv9i03bqBgj9KQ8E=
    environment:
      - BITCOIN_ABC_DATA=/var/lib/bitcoin-cash
    logging:
      options:
        max-size: "50m"
    networks:
      - scrapers-network
    deploy:
      mode: global
      restart_policy:
        delay: 2s
        window: 20s
        
  tron:
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/api-golang/blockchain-scrapers/blochains/tron/node/Dockerfile-tron
    image:
      ${DOCKER_HUB_LOGIN}/blockchain-scrapers_tron
    ports:
      - "50051"
      - "18888"
    working_dir: /java-tron/build/libs
    command: bash -c "java -jar java-tron.jar --witness"
    logging:
      options:
        max-size: "50m"
    networks:
      - scrapers-network
    deploy:
      mode: global
      restart_policy:
        delay: 2s
        window: 20s
        
  btc:
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/api-golang/blockchain-scrapers/blockchains/bitcoin/node/Dockerfile-btc
    image: ${DOCKER_HUB_LOGIN}/blockchain-scrapers_btc
    networks:
      - scrapers-network
    logging:
      options:
        max-size: "50m"
    secrets:
      - api_diadata
      
  ltc:
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/api-golang/blockchain-scrapers/blockchains/litecoin/node/Dockerfile-ltc
    image: ${DOCKER_HUB_LOGIN}/blockchain-scrapers_ltc
    networks:
      - scrapers-network
    logging:
      options:
        max-size: "50m"
    secrets:
      - api_diadata

  erc20:
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/api-golang/blockchain-scrapers/blockchains/ethereum/node/Dockerfile-erc20
    image: ${DOCKER_HUB_LOGIN}/blockchain-scrapers_erc20
    command: -symbol BNB -address "0xB8c77482e45F1F44dE1745F52C74426C631bDD52"
    networks:
      - scrapers-network
    logging:
      options:
        max-size: "50m"
    secrets:
      - api_diadata
  eth:
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/api-golang/blockchain-scrapers/blockchains/ethereum/node/Dockerfile-eth
    image: ${DOCKER_HUB_LOGIN}/blockchain-scrapers_eth
    networks:
      - scrapers-network
    logging:
      options:
        max-size: "50m"
    secrets:
      - api_diadata
  ada:
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/api-golang/blockchain-scrapers/blockchains/cardano/node/Dockerfile-ada
    image: ${DOCKER_HUB_LOGIN}/blockchain-scrapers_ada
    networks:
      - scrapers-network
    logging:
      options:
        max-size: "50m"
    secrets:
      - api_diadata
  xlm:
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/api-golang/blockchain-scrapers/blockchains/stellar/node/Dockerfile-xlm
    image: ${DOCKER_HUB_LOGIN}/blockchain-scrapers_xlm
    networks:
      - scrapers-network
    logging:
      options:
        max-size: "50m"
    secrets:
      - api_diadata
  xrp:
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/api-golang/blockchain-scrapers/blockchains/ripple/node/Dockerfile-xrp
    image: ${DOCKER_HUB_LOGIN}/blockchain-scrapers_xrp
    networks:
      - scrapers-network
    logging:
      options:
        max-size: "50m"
    secrets:
      - api_diadata
  neo:
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/api-golang/blockchain-scrapers/blockchains/node/Dockerfile-neo
    image: ${DOCKER_HUB_LOGIN}/blockchain-scrapers_neo
    networks:
      - scrapers-network
    logging:
      options:
        max-size: "50m"
    secrets:
      - api_diadata
      
  xmr:
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/api-golang/blockchain-scrapers/blockchains/monero/node/Dockerfile-xmr
    image: ${DOCKER_HUB_LOGIN}/blockchain-scrapers_xmr
    networks:
    - scrapers-network
    logging:
      options:
        max-size: "50m"
    secrets:
      - api_diadata
      
  usdt:
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/api-golang/blockchain-scrapers/blockchains/tether/node/Dockerfile-usdt
    image: ${DOCKER_HUB_LOGIN}/blockchain-scrapers_usdt
    networks:
      - scrapers-network
    logging:
      options:
        max-size: "50m"
    secrets:
      - api_diadata

  trx:
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/api-golang/blockchain-scrapers/blockchains/tron/node/Dockerfile-trx
    image: ${DOCKER_HUB_LOGIN}/blockchain-scrapers_trx
    depends_on:
      - tron
    networks:
      - scrapers-network
    logging:
      options:
        max-size: "50m"
    secrets:
      - api_diadata
      
  bch:
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/api-golang/blockchain-scrapers/blockchains/bitcoin-cash/node/Dockerfile-bch
    image: ${DOCKER_HUB_LOGIN}/blockchain-scrapers_bch
    depends_on:
      - bitcoin-cash
    networks:
      - scrapers-network
    logging:
      options:
        max-size: "50m"
    secrets:
      - api_diadata

volumes:
  bitcoin:

networks:
  scrapers-network:

secrets:
  api_diadata:
    file: $GOPATH/src/github.com/diadata-org/api-golang/blockchain-scrapers/config/secrets/api_diadata.json
