FROM golang:latest as build

WORKDIR $GOPATH/src/

COPY . .

WORKDIR $GOPATH/src/github.com/diadata-org/api-golang/blockchain-scrapers/cmd/ada

RUN go install

FROM gcr.io/distroless/base

COPY --from=build /go/bin/ada /bin/ada

CMD ["ada"]
