FROM golang:latest as build

WORKDIR $GOPATH/src/

COPY . .

WORKDIR $GOPATH/src/github.com/diadata-org/api-golang/blockchain-scrapers/cmd

RUN go install

FROM gcr.io/distroless/base

COPY --from=build /go/bin/blockchain-scrapers /bin/blockchain-scrapers

CMD ["blockchain-scrapers"]
