# docker stack deploy -c docker-compose.yml blockchain-scrapers
version: '3.2'

services:
  bitcoind:
    image:
      kylemanna/bitcoind
    ports:
      - "8332"
    volumes:
      - /home/srv/bitcoind:/bitcoin
    command: btc_oneshot -printtoconsole -prune=550 -rpcallowip=::/0 -disablewallet -rpcpassword=mysecretrpcdiapassword -rpcuser=mysecretrpcdiauser
    logging:
      options:
        max-size: "50m"
    networks:
      - scrapers-network
    deploy:
      mode: global
      restart_policy:
        delay: 2s
        window: 20s
  litecoind:
    image:
      uphold/litecoin-core
    ports:
      - "9332"
    volumes:
      - /home/srv/litecoind:/var/lib/litecoind
    command: -printtoconsole -prune=550 -rpcallowip=::/0 -disablewallet -rpcuser=mysecretrpcdiauser -rpcpassword=njTcaNX74sSf46_TXacMVlyPMJjuv9i03bqBgj9KQ8E=

    environment:
      - LITECOIN_DATA=/var/lib/litecoind
    logging:
      options:
        max-size: "50m"
    networks:
      - scrapers-network
    deploy:
      mode: global
      restart_policy:
        delay: 2s
        window: 20s
  geth:
    image:
      ethereum/client-go:alpine
    ports:
      - "8545"
      - "30303"
    volumes:
      - /home/srv/geth:/root/.ethereum
    command: --rpcvhosts geth --rpc --rpcaddr "0.0.0.0" --syncmode "light" --cache 1024 --rpc

    logging:
      options:
        max-size: "50m"
    networks:
      - scrapers-network
    deploy:
      mode: global
      restart_policy:
        delay: 2s
        window: 20s
  cardano:
    image:
      eristoddle/cardano-explorer
    ports:
      - "8100"
    volumes:
      - /home/srv/cardano:/home/cardano/cardano-sl/state-explorer-mainnet
    logging:
      options:
        max-size: "50m"
    networks:
      - scrapers-network
    deploy:
      mode: global
      restart_policy:
        delay: 2s
        window: 20s
  btc:
    build:
      context: ../../../..
      dockerfile: github.com/diadata-org/api-golang/blockchain-scrapers/Dockerfile-btc
    image: ${DOCKER_HUB_LOGIN}/blockchain-scrapers_btc
    networks:
      - scrapers-network
    logging:
      options:
        max-size: "50m"
    secrets:
      - api_diadata
  ltc:
    build:
      context: ../../../..
      dockerfile: github.com/diadata-org/api-golang/blockchain-scrapers/Dockerfile-ltc
    image: ${DOCKER_HUB_LOGIN}/blockchain-scrapers_ltc
    networks:
      - scrapers-network
    logging:
      options:
        max-size: "50m"
    secrets:
      - api_diadata
  erc20:
    build:
      context: ../../../..
      dockerfile: github.com/diadata-org/api-golang/blockchain-scrapers/Dockerfile-erc20
    image: ${DOCKER_HUB_LOGIN}/blockchain-scrapers_erc20
    command: -symbol BNB -address "0xB8c77482e45F1F44dE1745F52C74426C631bDD52"
    networks:
      - scrapers-network
    logging:
      options:
        max-size: "50m"
    secrets:
      - api_diadata
  eth:
    build:
      context: ../../../..
      dockerfile: github.com/diadata-org/api-golang/blockchain-scrapers/Dockerfile-eth
    image: ${DOCKER_HUB_LOGIN}/blockchain-scrapers_eth
    networks:
      - scrapers-network
    logging:
      options:
        max-size: "50m"
    secrets:
      - api_diadata
  ada:
    build:
      context: ../../../..
      dockerfile: github.com/diadata-org/api-golang/blockchain-scrapers/Dockerfile-ada
    image: ${DOCKER_HUB_LOGIN}/blockchain-scrapers_ada
    networks:
      - scrapers-network
    logging:
      options:
        max-size: "50m"
    secrets:
      - api_diadata
volumes:
  bitcoin:

networks:
  scrapers-network:

secrets:
  api_diadata:
    file: config/secrets/api_diadata.json
