# docker stack deploy -c docker-compose.yml blockchain-scrapers 
version: '3.2'

services:
  bitcoind:
    image:
      kylemanna/bitcoind
    ports:
      - "8332"
    volumes:
      - /home/srv/bitcoind:/bitcoin
    command: btc_oneshot -prune=550 -rpcallowip=::/0 -disablewallet -rpcpassword=mysecretrpcdiapassword -rpcuser=mysecretrpcdiauser
    logging:
      options:
        max-size: "50m"
    networks:
      - scrapers-network
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.bitcoind==true
      restart_policy:
        delay: 2s
        window: 20s

  btc: 
    build:
      context: ../../../..
      dockerfile: github.com/diadata-org/api-golang/blockchain-scrapers/Dockerfile-btc
    image: blockchain-scrapers_btc 
    networks:
      - scrapers-network
    logging:
      options:
        max-size: "50m"
    secrets:
      - api_diadata

volumes:
  bitcoin:

networks:
  scrapers-network:

secrets:
  api_diadata:
    file: config/secrets/api_diadata.json