FROM golang:latest as build

RUN go get github.com/PaddyMc/go-tron/calculations

WORKDIR $GOPATH/src/

COPY . .

WORKDIR $GOPATH/src/github.com/diadata-org/api-golang/blockchain-scrapers/cmd/trx

RUN go install

FROM gcr.io/distroless/base

COPY --from=build /go/bin/trx /bin/trx

CMD ["trx"]