FROM golang:latest as build

WORKDIR $GOPATH

COPY . .

WORKDIR $GOPATH/src/github.com/diadata-org/diadata/blockchain-scrapers/blockchains/ripple/scrapers/xrp

RUN go install

FROM gcr.io/distroless/base

COPY --from=build /go/bin/xrp /bin/xrp

CMD ["xrp"]
