apiVersion: apps/v1
kind: Deployment
metadata:
  name: filtersblockservice
  labels:
    app: filtersblockservice
spec:
  selector:
    matchLabels:
      app: filtersblockservice
  template:
    metadata:
      labels:
        app: filtersblockservice
    spec:
      containers:
        - name: filtersblockservice
          image: __IMAGE__@__DIGEST__
          ports:
            - name: http-server
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: filtersblockservice
  labels:
    app: filtersblockservice
spec:
  ports:
    - port: 8080
      targetPort: http-server
  selector:
    app: filtersblockservice
  type: NodePort
