apiVersion: batch/v1
kind: Job
metadata:
  name: job-prepare
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      containers:
        - name: job-prepare-blockchainservice
          image: dia.blockchainservice.dev:latest
          imagePullPolicy: IfNotPresent
          command: ["blockchainservice"]
          args: []
          env:
            - name: USE_ENV
              value: "true"
            - name: POSTGRES_HOST
              value: "data-postgres.default.svc.cluster.local"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "postgres"
        - name: job-prepare-assetcollectionservice-ethassets
          image: dia.assetcollectionservice.dev:latest
          imagePullPolicy: Never
          command: ["assetCollectionService"]
          args: ["-source=assetlists", "-secret=eth_assets", "-caching=true"]
          env:
            - name: USE_ENV
              value: "true"
            - name: POSTGRES_HOST
              value: "data-postgres.default.svc.cluster.local"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "postgres"
            - name: REDISURL
              value: "data-redis.default.svc.cluster.local:6379"
        - name: job-prepare-assetcollectionservice-nonethassets
          image: dia.assetcollectionservice.dev:latest
          imagePullPolicy: Never
          command: ["assetCollectionService"]
          args:
            ["-source=assetlists", "-secret=non_eth_assets", "-caching=true"] # skipcq: SCT-A000
          env:
            - name: USE_ENV
              value: "true"
            - name: POSTGRES_HOST
              value: "data-postgres.default.svc.cluster.local"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "postgres"
            - name: REDISURL
              value: "data-redis.default.svc.cluster.local:6379"
        - name: job-prepare-assetcollectionservice-fiatassets
          image: dia.assetcollectionservice.dev:latest
          imagePullPolicy: Never
          command: ["assetCollectionService"]
          args: ["-source=assetlists", "-secret=fiat_assets", "-caching=true"] # skipcq: SCT-A000
          env:
            - name: USE_ENV
              value: "true"
            - name: POSTGRES_HOST
              value: "data-postgres.default.svc.cluster.local"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "postgres"
            - name: REDISURL
              value: "data-redis.default.svc.cluster.local:6379"
      initContainers:
        - name: check-postgres-connection
          image: public.ecr.aws/docker/library/postgres:15-alpine
          env:
            - name: PGHOST
              value: "data-postgres.default.svc.cluster.local"
            - name: PGUSER
              value: "postgres"
            - name: PGPASSWORD
              value: "password"
          command:
            [
              "sh",
              "-c",
              "until pg_isready -h $PGHOST -U $PGUSER; do sleep 1; done",
            ]
        - name: check-redis-connection
          image: public.ecr.aws/docker/library/redis:7
          env:
            - name: REDISCLI_URL
              value: "redis://data-redis.default.svc.cluster.local:6379/0"
          command:
            [
              "sh",
              "-c",
              "until redis-cli -u $REDISCLI_URL ping; do sleep 1; done",
            ]
        - name: check-influxdb-connection
          image: public.ecr.aws/docker/library/influxdb:1.8
          env:
            - name: INFLUXDB_URL
              value: "data-influx.default.svc.cluster.local"
            - name: INFLUXDB_USERNAME
              value: "test"
            - name: INFLUXDB_PASSWORD
              value: "testtest"
          command:
            [
              "sh",
              "-c",
              "until influx -host $INFLUXDB_URL -username $INFLUXDB_USERNAME -password $INFLUXDB_PASSWORD -execute 'SHOW DATABASES'; do sleep 1; done",
            ]
        - name: check-kafka-connection
          image: confluentinc/cp-kafkacat:6.2.1
          env:
            - name: KAFKA_BROKER_URL
              value: "data-kafka.default.svc.cluster.local:9094"
          command:
            [
              "sh",
              "-c",
              "until kafkacat -b $KAFKA_BROKER_URL -L; do sleep 1; done",
            ]
      restartPolicy: Never
  backoffLimit: 0
