version: '3.2'

services:
  bitcoin:
    image:
      kylemanna/bitcoind
    ports:
      - "8332"
    volumes:
      - $HOME/srv/bitcoin:/bitcoin
    command: btc_oneshot -printtoconsole -prune=550 -rpcallowip=::/0 -disablewallet -rpcpassword=mysecretrpcdiapassword -rpcuser=mysecretrpcdiauser
    logging:
      options:
        max-size: "50m"
    networks:
      - scrapers-network
    deploy:
      mode: global
      restart_policy:
        delay: 2s
        window: 20s

  btc:
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/api-golang/blockchain-scrapers/blockchains/bitcoin/node/Dockerfile
    image: ${DOCKER_HUB_LOGIN}/blockchain-scrapers_btc
    networks:
      - scrapers-network
    logging:
      options:
        max-size: "50m"
    secrets:
      - api_diadata

secrets:
  api_diadata:
    file: $GOPATH/src/github.com/diadata-org/api-golang/blockchain-scrapers/config/secrets/api_diadata.json

volumes: 
  bitcoin:

networks: 
  scrapers-network: