FROM golang:latest as build

WORKDIR $GOPATH/src/

COPY . .

WORKDIR $GOPATH/src/github.com/diadata-org/api-golang/services/filtersBlockService

RUN go install

FROM gcr.io/distroless/base

COPY --from=build /go/bin/filtersBlockService /bin/filtersBlockService
COPY --from=build /go/src/github.com/diadata-org/api-golang/exchange-scrapers/config /config/

CMD ["filtersBlockService"]