FROM golang:latest as build

WORKDIR $GOPATH

COPY . .

WORKDIR $GOPATH/src/github.com/diadata-org/diadata/blockchain-scrapers/blockchains/monero/scrapers/xmr

RUN go install

FROM gcr.io/distroless/base

COPY --from=build /go/bin/xmr /bin/xmr

ENTRYPOINT ["xmr"]
