FROM golang:latest as build

WORKDIR $GOPATH/src/

COPY . .

WORKDIR $GOPATH/src/github.com/diadata-org/api-golang/exchange-scrapers/ecb

RUN go install

FROM gcr.io/distroless/base

COPY --from=build /go/bin/ecb /bin/ecb
COPY --from=build /go/src/github.com/diadata-org/api-golang/config/ /config/

CMD ["ecb"]
