apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-lint-deploy-tekton-ci
  namespace: tekton-pipelines
spec:
  pipelineRef:
    name: build-lint-create-deploy
  resources:
    - name: git-source
      resourceRef:
        name: git-diadata-tekton-ci
  params:
    - name: path-to-context
      value: "/workspace/git-source/"
    - name: path-to-yaml-file
      value: "deployments/k8s-yaml/filtersblockservice.yaml"
    - name: "image-url"
      value: "us.icr.io/dia-registry/scraper/filtersblockservice"
    - name: "image-tag"
      value: "latest"
    - name: path-to-dockerfile
      value: "/build/Dockerfile-filtersBlockService"
  serviceAccountName: ibm-cr
