version: '3.2'

services:
  bitcoin-cash:
    image:
      uphold/bitcoin-abc
    ports:
      - "8332"
    volumes:
      - $HOME/srv/bitcoin-cash:/var/lib/bitcoin-cash
    command: -printtoconsole -prune=550 -rpcallowip=::/0 -disablewallet -rpcuser=mysecretrpcdiauser -rpcpassword=njTcaNX74sSf46_TXacMVlyPMJjuv9i03bqBgj9KQ8E=
    environment:
      - BITCOIN_ABC_DATA=/var/lib/bitcoin-cash
    logging:
      options:
        max-size: "50m"
    networks:
      - scrapers-network
    deploy:
      mode: global
      restart_policy:
        delay: 2s
        window: 20s
        
  bch:
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/api-golang/blockchain-scrapers/blockchains/bitcoin-cash/node/Dockerfile-bch
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_bch
    depends_on:
      - bitcoin-cash
    networks:
      - scrapers-network
    logging:
      options:
        max-size: "50m"
    secrets:
      - api_diadata


secrets:
  api_diadata:
    file: $GOPATH/src/github.com/diadata-org/api-golang/blockchain-scrapers/config/secrets/api_diadata.json

volumes: 
  bitcoin:

networks: 
  scrapers-network: