apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-create-deploy
  namespace: tekton-pipelines
spec:
  resources:
    - name: git-source
      type: git
  params:
    - name: path-to-context
      description: The path to the build context, used by Kaniko - within the workspace
      default: .
    - name: path-to-dockerfile
      description: The path to the dockerfile
    - name: path-to-yaml-file
      description: The path to the yaml file to deploy within the git source
      default: config.yaml
    - name: image-url
      description: Url of image repository
      default: deploy_target
    - name: image-tag
      description: Tag to apply to the built image
      default: latest
  tasks:
    - name: build
      taskRef:
        name: golang-build
      resources:
        inputs:
          - name: git-source
            resource: git-source
    - name: kaniko-build-docker
      taskRef:
        name: kaniko-build-docker
      params:
        - name: path-to-context
          value: "$(params.path-to-context)"
        - name: path-to-dockerfile
          value: "$(params.path-to-dockerfile)"
        - name: image-url
          value: "$(params.image-url)"
        - name: image-tag
          value: "$(params.image-tag)"
      resources:
        inputs:
          - name: git-source
            resource: git-source
      runAfter:
        - build
    - name: deploy-application
      taskRef:
        name: deploy-application
      runAfter:
        - kaniko-build-docker
      params:
        - name: path-to-context
          value: "$(params.path-to-context)"
        - name: path-to-yaml-file
          value: "$(params.path-to-yaml-file)"
        - name: image-url
          value: "$(params.image-url)"
        - name: image-tag
          value: "$(params.image-tag)"
      resources:
        inputs:
          - name: git-source
            resource: git-source
