apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: golangci-lint
  namespace: tekton-pipelines
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: lint
    tekton.dev/displayName: "golangci lint"
spec:
  description: >-
    This Task is Golang task to validate Go projects.
  params:
#    - name: package
#      description: base package (and its children) under validation
    - name: flags
      description: flags to use for the test command
      default: --verbose
    - name: config
      description: config file to be used
      default: /workspace/src/.golangci.yml
    - name: version
      description: golangci-lint version to use
      default: "v1.39"
    - name: GOOS
      description: "running operating system target"
      default: linux
    - name: GOARCH
      description: "running architecture target"
      default: amd64
    - name: GO111MODULE
      description: "value of module support"
      default: auto
  resources:
    inputs:
      - name: git-source
        type: git
        targetPath: src/
  steps:
    - name: lint
      image: docker.io/golangci/golangci-lint:$(params.version)
      workingDir: $(resources.inputs.git-source.path)
      script: |
        golangci-lint run $(params.flags)  --config=$(params.config)
      env:
        - name: GOPATH
          value: /workspace
        - name: GOOS
          value: "$(params.GOOS)"
        - name: GOARCH
          value: "$(params.GOARCH)"
        - name: GO111MODULE
          value: "$(params.GO111MODULE)"
