FROM golang:latest as build

WORKDIR $GOPATH

COPY . .

WORKDIR $GOPATH/src/github.com/diadata-org/diadata/blockchain-scrapers/blockchains/cardano/scrapers/

RUN go install

FROM gcr.io/distroless/base

COPY --from=build /go/bin/scrapers /bin/ada

CMD ["ada"]
