// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: protoc/signer.proto

package signer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type SignedData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signed []byte `protobuf:"bytes,1,opt,name=signed,proto3" json:"signed,omitempty"`
}

func (x *SignedData) Reset() {
	*x = SignedData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_signer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedData) ProtoMessage() {}

func (x *SignedData) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_signer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedData.ProtoReflect.Descriptor instead.
func (*SignedData) Descriptor() ([]byte, []int) {
	return file_protoc_signer_proto_rawDescGZIP(), []int{0}
}

func (x *SignedData) GetSigned() []byte {
	if x != nil {
		return x.Signed
	}
	return nil
}

type DataToSign struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	By   string `protobuf:"bytes,2,opt,name=by,proto3" json:"by,omitempty"`
}

func (x *DataToSign) Reset() {
	*x = DataToSign{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_signer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataToSign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataToSign) ProtoMessage() {}

func (x *DataToSign) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_signer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataToSign.ProtoReflect.Descriptor instead.
func (*DataToSign) Descriptor() ([]byte, []int) {
	return file_protoc_signer_proto_rawDescGZIP(), []int{1}
}

func (x *DataToSign) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataToSign) GetBy() string {
	if x != nil {
		return x.By
	}
	return ""
}

var File_protoc_signer_proto protoreflect.FileDescriptor

var file_protoc_signer_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2f, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63, 0x22, 0x24, 0x0a, 0x0a, 0x53, 0x69,
	0x67, 0x6e, 0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x69, 0x67, 0x6e,
	0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64,
	0x22, 0x30, 0x0a, 0x0a, 0x44, 0x61, 0x74, 0x61, 0x54, 0x6f, 0x53, 0x69, 0x67, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x62, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x62, 0x79, 0x32, 0x34, 0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x04,
	0x53, 0x69, 0x67, 0x6e, 0x12, 0x0f, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x54,
	0x6f, 0x53, 0x69, 0x67, 0x6e, 0x1a, 0x0f, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x69, 0x67, 0x6e,
	0x65, 0x64, 0x44, 0x61, 0x74, 0x61, 0x22, 0x00, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x69, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2d, 0x6f,
	0x72, 0x67, 0x2f, 0x64, 0x69, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x64,
	0x69, 0x61, 0x2f, 0x68, 0x65, 0x6c, 0x70, 0x65, 0x72, 0x2f, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protoc_signer_proto_rawDescOnce sync.Once
	file_protoc_signer_proto_rawDescData = file_protoc_signer_proto_rawDesc
)

func file_protoc_signer_proto_rawDescGZIP() []byte {
	file_protoc_signer_proto_rawDescOnce.Do(func() {
		file_protoc_signer_proto_rawDescData = protoimpl.X.CompressGZIP(file_protoc_signer_proto_rawDescData)
	})
	return file_protoc_signer_proto_rawDescData
}

var file_protoc_signer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protoc_signer_proto_goTypes = []interface{}{
	(*SignedData)(nil), // 0: rpc.SignedData
	(*DataToSign)(nil), // 1: rpc.DataToSign
}
var file_protoc_signer_proto_depIdxs = []int32{
	1, // 0: rpc.Signer.Sign:input_type -> rpc.DataToSign
	0, // 1: rpc.Signer.Sign:output_type -> rpc.SignedData
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protoc_signer_proto_init() }
func file_protoc_signer_proto_init() {
	if File_protoc_signer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protoc_signer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignedData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoc_signer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataToSign); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protoc_signer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protoc_signer_proto_goTypes,
		DependencyIndexes: file_protoc_signer_proto_depIdxs,
		MessageInfos:      file_protoc_signer_proto_msgTypes,
	}.Build()
	File_protoc_signer_proto = out.File
	file_protoc_signer_proto_rawDesc = nil
	file_protoc_signer_proto_goTypes = nil
	file_protoc_signer_proto_depIdxs = nil
}
