version: '3.2'

services:
  usdt:
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/api-golang/blockchain-scrapers/blockchains/tether/node/Dockerfile-usdt
    image: ${DOCKER_HUB_LOGIN}/blockchain-scrapers_usdt
    networks:
      - scrapers-network
    logging:
      options:
        max-size: "50m"
    secrets:
      - api_diadata

secrets:
  api_diadata:
    file: $GOPATH/src/github.com/diadata-org/api-golang/blockchain-scrapers/config/secrets/api_diadata.json

volumes: 
  bitcoin:

networks: 
  scrapers-network: