FROM golang:latest as build

WORKDIR $GOPATH

COPY . .

WORKDIR $GOPATH/src/github.com/diadata-org/api-golang/blockchain-scrapers/blockchains/dash/scrapers/dash

RUN go install

FROM gcr.io/distroless/base

COPY --from=build /go/bin/dash /bin/dash

CMD ["dash"]