version: '3.2'

services:
  litecoin:
    image:
      uphold/litecoin-core
    ports:
      - "9332"
    volumes:
      - $HOME/srv/litecoin:/var/lib/litecoin
    command: -printtoconsole -prune=550 -rpcallowip=::/0 -disablewallet -rpcuser=mysecretrpcdiauser -rpcpassword=njTcaNX74sSf46_TXacMVlyPMJjuv9i03bqBgj9KQ8E=

    environment:
      - LITECOIN_DATA=/var/lib/litecoin
    logging:
      options:
        max-size: "50m"
    networks:
      - scrapers-network
    deploy:
      mode: global
      restart_policy:
        delay: 2s
        window: 20s
        
  ltc:
    build:
      context: $GOPATH
      dockerfile: $GOPATH/src/github.com/diadata-org/api-golang/blockchain-scrapers/blockchains/litecoin/node/Dockerfile-ltc
    image: ${DOCKER_HUB_LOGIN}/${STACKNAME}_ltc
    networks:
      - scrapers-network
    logging:
      options:
        max-size: "50m"
    secrets:
      - api_diadata


secrets:
  api_diadata:
    file: $GOPATH/src/github.com/diadata-org/api-golang/blockchain-scrapers/config/secrets/api_diadata.json

volumes: 
  bitcoin:

networks: 
  scrapers-network: